### ISSUE TITLE
[bug] Account Modal Fails to Close

### ISSUE THREAD

**Issue by emmajane1313** [rainbow-me/rainbowkit#852] opened 2022-11-01 11:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.4

### wagmi Version

0.7.9

### Current Behavior

The account modal close button (cross in the top right corner of the pop up) sometimes does not close when clicked. The page needs to be refreshed for the modal to disappear from the screen.

### Expected Behavior

The modal should close when clicked. 

### Steps To Reproduce

1. Connect wallet to rainbow kit. Click on the display address/name to open the account modal. Click on close modal cross button.
2. Connect wallet to rainbow kit. Click on the display address/name to open the account modal. Click on disconnect. Click on close modal cross button.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://f3manifesto.xyz/collect/cargo

### Anything else?

This error is intermittent. I have tried to remove items / have the connect wallet button on a page to try and isolate a potential issue.

**Comment by outdoteth** [comment] 2022-11-01 11:53
I am getting the same issue

**Comment by stefan-girlich** [comment] 2022-11-01 13:41
@emmajane1313 duplicate of #837  ?

**Comment by emmajane1313** [comment] 2022-11-01 14:49
> 

ah seems to be, sorry completely missed that

**Comment by nickbytes** [comment] 2022-11-02 18:07
Closed as dupe.

**Closed by nickbytes** 2022-11-02 18:07 UTC
