### ISSUE TITLE
[bug] Modal dosent reopens and closes abruptly when i click on wallet in wallet list

### ISSUE THREAD

**Issue by mominnawaf** [rainbow-me/rainbowkit#1548] opened 2023-10-06 17:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.1.0

### wagmi Version

1.4.3

### Current Behavior

When I click on a wallet from the wallet list the modal closes, after which I'm unable to reopen the modal.

### Expected Behavior

Modal should open even if it is previously opened. 

### Anything else?

Here is my code

```ts
import React from 'react'
import '@rainbow-me/rainbowkit/styles.css'
import { getDefaultWallets, RainbowKitProvider, useConnectModal } from '@rainbow-me/rainbowkit'
import { configureChains, createConfig, WagmiConfig } from 'wagmi'
import { mainnet, polygon, polygonMumbai, goerli } from 'wagmi/chains'
import { publicProvider } from 'wagmi/providers/public'

const { chains, publicClient } = configureChains(
  [mainnet, polygon, polygonMumbai, goerli], 
  [publicProvider()]
)

const { connectors } = getDefaultWallets({
  appName: 'RainbowKit demo',
  projectId: import.meta.env.VITE_WALLET_CONNECT_PROJECT_ID, // valid
  chains
})

const wagmiConfig = createConfig({
  autoConnect: false,
  connectors,
  publicClient
})

const RainbowKitComp = (): React.JSX.Element => {
  const { openConnectModal } = useConnectModal()

  const openModal = (): void => {
    openConnectModal?.()
  }

  return <button onClick={openModal}> Connect</button>
}
const App = (): React.JSX.Element => {
  return <WagmiConfig config={wagmiConfig}>
        <RainbowKitProvider chains={chains}>
            <RainbowKitComp />
        </RainbowKitProvider>
    </WagmiConfig>
}

```

**Comment by DanielSinclair** [comment] 2023-10-06 23:06
@mominnawaf Can you share a CodeSandbox example? Please also provide the device and browser that you tested this flow with, and which wallet connector was affected.

**Comment by hieuhlc** [comment] 2023-10-11 03:16
I got this issue as well. Turns out my account was already connected and the connect modal won't open until I disconnect my account.

**Comment by DanielSinclair** [comment] 2023-12-28 06:49
Closing as I was unable to replicate the issue/unexpected behavior, but can reopen if you believe this issue persists.

**Closed by DanielSinclair** 2023-12-28 06:49 UTC
