### ISSUE TITLE
[bug] Connect Modal clips the right side of the body when opened

### ISSUE THREAD

**Issue by Sam-Scolari** [rainbow-me/rainbowkit#425] opened 2022-05-25 19:50 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

0.1.2

### wagmi Version

0.3.5

### Current Behavior

Before clicking Connect Wallet:
![Screenshot_70](https://user-images.githubusercontent.com/56174573/170354466-5b089bd6-4fa9-456b-9c7f-de3726ffade2.jpg)

After opening the Connect Modal:
![Screenshot_71](https://user-images.githubusercontent.com/56174573/170354358-8baeb9d0-aee2-48c4-940d-abd165a96d7f.jpg)

### Expected Behavior

The right side should not be clipped exposing the background of the body.

### Steps To Reproduce

I experience this one my own project but I noticed it occurs on the RainbowKit homepage as well.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

### Anything else?

Fixed positioned elements do not get clipped.

**Comment by tmwBuidls** [comment] 2022-06-15 15:02
FYI I don't think this is a bug. I investigated this myself and it's due to the `react-remove-scroll` package I believe, without it when the scrollbar is removed you get a visual glitch as the whole page increases in width a few pixels. Whereas this adds a dynamic margin to prevent the glitch.

If you don't want this behaviour then your best bet right now is probably to patch the package, which I tried and it worked. But then I preferred the current behaviour in the end so reverted. Hope that's helpful

**Comment by markdalgleish** [comment] 2022-06-20 01:16
This is by design (managed by `react-remove-scroll`, as @tmwBuidls mentioned) to avoid page content moving around when opening/closing the modal since scrolling is disabled when the modal is open which removes the scrollbar.

You can design around this by allowing elements to extend horizontally beyond the bounds of the page container, and react-remove-scroll also sets a CSS variable called `--removed-body-scroll-bar-size` that you can leverage in your layouts, but unfortunately it's not possible for the library to manage this automatically.

I'm closing this for now as it's not a bug, but feel free to raise a discussion if you'd like to talk about this further.

**Closed by markdalgleish** 2022-06-20 01:16 UTC
