### ISSUE TITLE
[bug] rainbowkit-siwe-next-auth not triggered Sign message/authorize callback if there is existing authentication 

### ISSUE THREAD

**Issue by alexshelkov** [rainbow-me/rainbowkit#1864] opened 2024-03-16 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

I am using nex-auth and rainbowkit-siwe-next-auth, and having already signup via Twitter/Discord (or any auth provider), then I am trying to connect the wallet.
The wallet getting connected (the button shows the address), but the "Sign message" flow is not triggered, so there is no proper authentication flow.

### Expected Behavior

The "Sign message" flow should work as usual, and the authorize callback must be called.

### Steps To Reproduce

Use next-auth with rainbowkit-siwe-next-auth:
- Sign in with Twitter
- Sign in with Randbow Kit

**Comment by magiziz** [comment] 2024-03-16 13:40
@alexshelkov We don't have a good example for the social authentication like twitter and discord, but it sounds like next authenticates the user once they sign up or sign in through twitter and discord which makes the "Sign message" not show up. If that's the case then that's the expected behaviour since we only show "Sign message" part if the user is not authenticated yet.

Please have a look at our custom authentication documentation here: https://www.rainbowkit.com/docs/custom-authentication#creating-a-custom-adapter

Here is also another example of how we use next-auth with RainbowKit: https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-siwe-next-auth

**Comment by magiziz** [comment] 2024-03-28 11:36
Closing this issue for now. Feel free to re-open this if you're stuck.

**Closed by magiziz** 2024-03-28 11:36 UTC
