### ISSUE TITLE
Switch Networks  Your wallet does not support switching networks from Rainbowkit Demo. Try switching networks from within your wallet instead.

### ISSUE THREAD

**Issue by Morgosh** [rainbow-me/rainbowkit#1500] opened 2023-09-04 12:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^1.0.10

### wagmi Version

^1.2.0

### Current Behavior

When I open nextjs localhost app, or the live version app and I click on switch network I receive this:

Your wallet does not support switching networks from Rainbowkit Demo. Try switching networks from within your wallet instead.

**BUT**, if I refresh the website all the networks appear. Just on the first visit, and for some reason it doesn't detect the networks.

Note that I testned on both my app, and existing demo applicaiton from official repo and I get the same error

https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next/pages/_app.tsx

**Comment by DanielSinclair** [comment] 2023-09-05 05:03
@Morgosh Which wallet(s) are you testing this flow with? Will attempt to reproduce.

**Comment by DanielSinclair** [comment] 2023-09-14 16:18
@Morgosh Bumping this; can investigate with some more information about your test path and wallet.

**Comment by KosmosKey** [comment] 2024-01-21 22:25
@Morgosh Are you still seeing this issue ? Can't reproduce this on my end. It might be the same issue mentioned here: https://github.com/wevm/wagmi/discussions/343

Let me know if you can also share a small reproducible example

**Comment by ene5135** [comment] 2024-01-23 09:07
@KosmosKey 

I'm having the same problem. 
It can be reproduced on the demo dapp (https://codesandbox.io/p/devbox/with-create-react-app-qqp2xl?file=%2Fsrc%2FApp.tsx) in the following order.
1. open the demo dapp 
2. connect wallet
3. in the wallet, change the chain to one that is not supported by the dapp (e.g. linea)
4. open a new tab (several times)
5. (wallet will be connected automatically)
6. click on wrong network button
7. You will see `Your wallet does not support switching networks from this app. Try switching networks from within your wallet instead` message

https://github.com/rainbow-me/rainbowkit/assets/24788756/7998e081-15ff-4c8e-aca3-16e97548e77a

**Comment by KosmosKey** [comment] 2024-01-24 17:50
@ene5135 That's super useful. Thank you for the reproducible example will have look into this and report back once this is fixed 👍

**Comment by KosmosKey** [comment] 2024-02-03 03:02
@ene5135 This will be fixed in RainbowKit v2. Issue seems to be that `wagmi` won't return `switchChain` if you haven't entered the app with the correct one or at least one of the chains which your dApp supports.

All this will be fixed in this PR: https://github.com/rainbow-me/rainbowkit/pull/1709

**Closed** 2024-02-03 03:02 UTC
