### ISSUE TITLE
[bug] rainbowkit v2 keeps blocking wallet message signing with report "oops, something went wrong!"

### ISSUE THREAD

**Issue by FrancoAguzzi** [rainbow-me/rainbowkit#1831] opened 2024-03-07 10:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

I have update my project's libraries to their latest versions but this made RainbowKit sign-in message to continuously trigger the modal "oops_error" ([falling in this conditional](https://github.com/rainbow-me/rainbowkit/blob/8b17b8fbec55ce252660ee89b7c129fb62f3a1f3/packages/rainbowkit/src/components/SignIn/SignIn.tsx#L121)). I'd love to use RainbowKit v2 but I am blocked from upgrading the library version due to this issue.

<img width="394" alt="Captura de Tela 2024-03-07 às 06 53 44" src="https://github.com/rainbow-me/rainbowkit/assets/49823133/add02473-9079-45aa-ae6b-143ee3fc1eda">

After cloning RainbowKit's repo and adding logs, I identified the issue is probably being triggered in this code line, present in the file mentioned above:

```
 const verified = await authAdapter.verify({ message, signature });
```

### Expected Behavior

I expect the sign message flow to work without problems

### Steps To Reproduce

The core packages versions I am using are:

```
    "@rainbow-me/rainbowkit": "2.0.1",
    "@rainbow-me/rainbowkit-siwe-next-auth": "0.4.0",
    "@tanstack/react-query": "4.26.1",
    "@wagmi/core": "2.6.5",
    "next": "14.1.1-canary.52",
    "next-auth": "4.24.5",
    "react": "18.2.0",
    "siwe": "2.1.4",
    "viem": "2.7.15",
    "wagmi": "2.5.7",
```

As you can infer from the list above, I am using NextAuth + Siwe to handle wallet authentication, here is my code for this:

```
import NextAuth from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import { SiweMessage } from "siwe";

export default NextAuth({
  providers: [
    CredentialsProvider({
      credentials: {
        message: {
          label: "Address",
          type: "text",
          placeholder: "Address",
        },
        signature: {
          label: "Signature",
          type: "text",
          placeholder: "Signature",
        },
      },
      authorize: async (credentials) => {
        const { message, signature } = credentials as any;
        const siweMessage = new SiweMessage(JSON.parse(message));
        const fields = await siweMessage.verify({ signature });

        const { data } = fields;
        const ethereumAddress = data.address.toLowerCase();

        return { id: ethereumAddress };
      },
    }),
  ],
  session: {
    maxAge: 365 * 24 * 60 * 60, // 1 year
  },
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        token.id = user.id;
      }
      return token;
    },
    async session({ session, token }) {
      session.user.id = token.id;
      return session;
    },
  },
});

```

### Anything else?

I would love to hear back from you soon

Appreciate your attention on this

Thank you

**Comment by KosmosKey** [comment] 2024-03-07 13:57
@FrancoAguzzi Thanks for raising this issue. I'll be happy to help you!

**Can you try doing the following ?** 
1. Check your `.env` file and see if you've got `NEXTAUTH_SECRET` and `NEXTAUTH_URL` variables
2. Clear browser cache. This might be useful if you've used RainbowKit v1 and instantly transitioned to v2
3. Assuming you've already used sign-in with ethereum (siwe) with RainbowKit v1, can you try to look at this [_app.tsx](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-siwe-next-auth/pages/_app.tsx) example and see if you have something missing ?

If you're still stuck with this please can you share a small reproducible example and mention what wallet you use when testing this ?

**Comment by magiziz** [comment] 2024-03-08 14:17
@FrancoAguzzi Going to close this issue for now. Please either reopen this issue if you're stuck or raise another issue if you've encountered another bug. Thanks!

**Closed by magiziz** 2024-03-08 14:17 UTC

**Comment by magiziz** [comment] 2024-03-13 13:59
@FrancoAguzzi In codesandbox it's not working, but if i clone it locally it seems to be working.

https://github.com/rainbow-me/rainbowkit/assets/53529533/9fbe5311-a3ee-4b8f-9e00-af2f68342952

Did you look at our[ _app.tsx](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-siwe-next-auth/pages/_app.tsx) example here ?

**Comment by FrancoAguzzi** [comment] 2024-03-14 20:45
Hey @magiziz , you are write, I have downloaded the Devbox and this is really working.

Unfortunately, in my application, which is quite big now and which I cannot expose most of its code in a CodeSandbox, the issue persists. 

Is there any possibility we can meet and I can show you my application and how Rainbow v2 does not work good in it?

I have looked your _app.tsx example and my _app.tsx looks very similar, with the exception of additional tags I have in mine.

I'd appreciate a lot if we could meet for 15 minutes some day 🙏🏼👨🏼‍💻

Thank you!

**Comment by magiziz** [comment] 2024-03-14 22:26
@FrancoAguzzi Got it. Yeah if you don't want to share your code in CodeSandbox that's fine. I really don't know what's the issue if i can't see the code. 

You would have to dig into it a bit more and see why it's not working, since it could be anything from the wallet you're using, next-auth setup (check docs [here](https://next-auth.js.org/)) and even RainbowKit auth provider setup (check docs [here](https://www.rainbowkit.com/docs/authentication) as well).

Our example works fine with no issues, but let me know if you've spotted the issue on your end.

Regarding having a meeting, i can't do meetings unfortunately 🥲
