### ISSUE TITLE
Hydration Errors after "npm init @rainbow-me/rainbowkit@latest"

### ISSUE THREAD

**Issue by devdacian** [rainbow-me/rainbowkit#944] opened 2023-01-10 02:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.0

### Current Behavior

After running "npm init @rainbow-me/rainbowkit@latest" then opening the browser I am greeted with the following 4 attached errors.

3 errors are hydration, one is unhandled runtime error due to no connection. I can get rid of this last error by changing "autoConnect: false" in _app.tsx when configuring the wagmi client, but I'm not sure what to do about the hydration errors.

My understanding is that these hydration errors used to be warnings but were made errors in React 18. From the package.json that was created by rainbowkit init:

  "dependencies": {
    "@rainbow-me/rainbowkit": "^0.8.1",
    "ethers": "^5.0.0",
    "next": "^12.1.6",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "wagmi": "^0.9.0"
  },
  "devDependencies": {
    "@types/node": "^17.0.35",
    "@types/react": "^18.0.9",
    "eslint": "^8.15.0",
    "eslint-config-next": "^12.1.6",
    "typescript": "^4.7.2"
  }

I also noticed that the example @ https://codesandbox.io/s/rainbowkit-nextjs-gz890p is using React 17. Try it on React 18 and see what happens :-)

### Expected Behavior

I wouldn't expect to see any errors after using the rainbowkit init, would expect the page to load normally with no errors.

### Steps To Reproduce

npm init @rainbow-me/rainbowkit@latest

npm run dev

Browse to http://localhost:3000/

### Anything else?

![Screenshot from 2023-01-09 21-57-40](https://user-images.githubusercontent.com/114125154/211447696-602fca7a-ea4d-4c31-a89b-ad2c60956245.png)
![Screenshot from 2023-01-09 21-57-45](https://user-images.githubusercontent.com/114125154/211447703-85f297c7-b0ed-40a8-b4ea-2075f5184306.png)
![Screenshot from 2023-01-09 21-57-48](https://user-images.githubusercontent.com/114125154/211447706-1a282eeb-d819-4263-9886-a53e6c892e2b.png)
![Screenshot from 2023-01-09 21-57-51](https://user-images.githubusercontent.com/114125154/211447709-191ea56c-8ecb-48a9-9cd7-d7182561593e.png)

**Comment by devdacian** [comment] 2023-01-10 11:54
I figured out how to fix this. In _app.tsx:

import { useEffect, useState } from 'react';

export default function App({ Component, pageProps }: AppProps) {
  const [ready, setReady] = useState(false)

  useEffect(() => {
    setReady(true)
  }, [])

  return (
    <>
      {ready ? (
        <WagmiConfig client={wagmiClient}>
          <RainbowKitProvider chains={chains}>
            <Component {...pageProps} />
          </RainbowKitProvider>
        </WagmiConfig>
      ) : null}
    </>
  )

No more hydration errors running on React 18

**Comment by DanielSinclair** [comment] 2023-01-11 19:19
@devdacian The `noNetwork` error is actually because the example API key for `alchemyProvider` supplied by Alchemy seems to have gone dead. We'll work to get a new API key or deprecate Alchemy in the examples. Just remove this line and exclusively use `publicProvider` instead.

For the hydration issues, I have been unable to reproduce. What Node version are you using?

**Comment by devdacian** [comment] 2023-01-11 20:16
I'm using Node 19.3.0, React 18.2.0 & NextJS 13.1.1. My understanding is the hydration errors only started popping up in React 18 (before that they were warnings that no one paid attention to), and that many are still using React 17 so aren't seeing them yet. Using the provided solution I no longer get the errors.

There is a twitter [thread](https://twitter.com/BowtiedSunda/status/1612929926998687744) around this issue as well where some SEO-related issues are discussed, as this solution can be sub-optimal from an SEO perspective without some additional modification.

**Comment by rafinskipg** [comment] 2023-01-12 09:26
+1

**Comment by daniel-quadrata** [comment] 2023-02-09 00:50
same issue, using only publicProvider()

**Comment by DanielSinclair** [comment] 2023-02-15 03:27
These issues should now be fixed with the latest Wagmi version. Opened #1024 to deprecate the default `alchemyProvider` key in the `create-rainbowkit` template as well.

**Closed by DanielSinclair** 2023-02-15 03:27 UTC
