### ISSUE TITLE
[bug] Metamask Issue in IOS Redirection Issue after connect or Sign & Switch Network Doesnt work on mobile

### ISSUE THREAD

**Issue by yashsisodiya** [rainbow-me/rainbowkit#1933] opened 2024-04-16 06:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

1. Connect your wallet with Metamask.
2. After a successful connection, Metamask doesn't redirect me back to the web, I need go back to the web manually.
3. Once I go back to the web page, the signer will be created. However, it may doesn't automatically redirect to Metamask.
4. To complete the process, I need to open Metamask manually and sign the transaction. andagain, it doesn't redirect me back to the web automatically.

and Also If the chain is not configured in Metamask it doesn't handle add or switch network process which works fine in Desktop Environment it directly gives error that chain is not configured

### Expected Behavior

1. Connect your wallet with Metamask.
2. After a successful connection, Metamask should redirect me back to the web.
3. Once I go back to the web page, the signer will be created.  it should automatically redirect to Metamask.
4. And Once I Sign it should redirect me back to the web automatically.

### Steps To Reproduce

Click and Connect Wallet and do rest Process

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://887fq3-3000.csb.app/

**Comment by magiziz** [comment] 2024-04-16 09:31
@yashsisodiya This is an expected behavior and something that's out of our control. On mobile we use WalletConnect to connect via MetaMask and they have some unexpected UX behaviors since it's a single chain wallet. You'll have to manually go back and fourth, but this should be fixed in the future and that's something which MetaMask and WalletConnect team is looking at right now.

Let me know if this makes sense 🙏

**Closed by magiziz** 2024-04-16 09:31 UTC

**Comment by magiziz** [comment] 2024-04-16 11:33
@yashsisodiya Same thing. WalletConnect and MetaMask team is working on fixing this 🙏

**Comment by anxiubin** [comment] 2024-08-19 06:37
any news?
