### ISSUE TITLE
[bug] Viem Big Int Issue

### ISSUE THREAD

**Issue by Deepsk315** [rainbow-me/rainbowkit#1457] opened 2023-08-08 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.8

### wagmi Version

1.3.9

### Current Behavior

I am not sure of how the issue is generating .

When i have created a fresh new project and added all dependency fields its working fine. but here i get this error : 
Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at ./node_modules/viem/dist/esm/constants/number.js (number.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/viem/dist/esm/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@wagmi/connectors/dist/chunk-QRUHVNWK.js (chunk-OQILYQDO.js:11:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@wagmi/connectors/dist/injected.js (injected.js:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@wagmi/core/dist/chunk-BVC4KGLQ.js (chunk-BVC4KGLQ.js:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@wagmi/core/dist/chunk-LAFZBYO7.js (chunk-EQOEZP46.js:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@wagmi/core/dist/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/wagmi/dist/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (web3.jpg:1:1)
    at ./src/components/ConnectMetaMask.js (ConnectMetaMask.js:245:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (Courses.js:18:1)
    at ./src/pages/Dashboard.js (Dashboard.js:18:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.css:7:1)
    at ./src/App.js (App.js:145:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.css:82:1)
    at ./src/index.js (index.js:37:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at 1 (format-string.js:10:1)
    at __webpack_require__ (bootstrap:856:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:99
    
    Dependency list : 
        "@rainbow-me/rainbowkit": "^1.0.8",
        "viem": "^1.5.3",
       "wagmi": "^1.3.9",
           "react-dom": "^18.2.0",
    "react": "^18.2.0",
    "react-scripts": "^4.0.3",

### Expected Behavior

It should not cause library issues even before i connect with wallet.

### Steps To Reproduce

- Add all the required functionality from rainbowkit docs here : https://www.rainbowkit.com/docs/installation
- issues comes after npm start

**Comment by ArshanKhanifar** [comment] 2023-08-11 21:15
yeah, I had this issue too. 

Seems to be an issue with Rainbow's metamask wallet connector: 
```
import { metaMaskWallet } from '@rainbow-me/rainbowkit/wallets';
```

Instead I'm importing the Metamask Wallet Connector from wagmi itself then passing that:
```
import { MetaMaskConnector } from "@wagmi/connectors/metaMask";
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: [new MetaMaskConnector({ chains })],
  publicClient,
});
```

**Comment by ArshanKhanifar** [comment] 2023-08-11 21:15
That fixed it for me.

**Comment by deepak-interakt** [comment] 2023-08-12 18:05
But you're only passing metamask connector to connectors , i need wallet connect and metamask both.

**Comment by DanielSinclair** [comment] 2023-08-15 16:42
@Deepsk315 Can you share a CodeSandbox example to reproduce the error? Investigating

**Comment by ArshanKhanifar** [comment] 2023-08-16 13:07
Sorry, I was too early to celebrate that did NOT actually fix it haha.

**Comment by DanielSinclair** [comment] 2023-08-18 04:34
This is more likely a viem problem or a conflict with your bundler. @ArshanKhanifar can you share a CodeSandbox example? Was unable to reproduce.

**Comment by DanielSinclair** [comment] 2023-08-22 03:12
Will close this for now as I am unable to reproduce, but can reopen if this issue persists. A CodeSandbox sample with your framework configuration and dependency tree would be helpful. Please also reference our [Build Tooling Setup](https://www.rainbowkit.com/docs/installation#additional-build-tooling-setup) guide.

**Comment by arsen39** [comment] 2023-08-27 16:02
I encounter the same error, but with a peculiar twist. When working with the development server (i.e., using npm start) in React, I face no errors. However, when I run the production build, I encounter the 'Uncaught TypeError: Cannot convert a BigInt value to a number' from number.ts:1. I initiated a new project to ensure there was no conflict with other dependencies and followed the same dependency setup as demonstrated in the [example](https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app). However, my setup was in JS rather than TS since my primary project is in JS. I can't seem to bypass this error during the build, especially since the code I'm working with is identical to the one in your example, with the aforementioned difference.

**Comment by JohnnyGoodpick** [comment] 2023-08-29 21:56
I get this error as well with the following lib
anything above this viem version makes rainbowkit returning this error
```
"siwe": "^2.1.4",
"viem": "1.6.1",
"wagmi": "^1.3.9",
"@rainbow-me/rainbowkit": "1.0.9",
"@rainbow-me/rainbowkit-siwe-next-auth": "0.3.0",
```

**Comment by JohnnyGoodpick** [comment] 2023-08-29 22:00
Here's the stacktrace, I believe it's an incompatability between viem version and rainbowkit

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at getWalletConnectConnector (file:///C:/work/sinaps/node_modules/@rainbow-me/rainbowkit/dist/index.js:303:33)
    at createConnector (file:///C:/work/sinaps/node_modules/@rainbow-me/rainbowkit/dist/index.js:544:50)
    at file:///C:/work/sinaps/node_modules/@rainbow-me/rainbowkit/dist/index.js:96:71
    at Array.forEach (<anonymous>)
    at file:///C:/work/sinaps/node_modules/@rainbow-me/rainbowkit/dist/index.js:73:21
    at new Config (file:///C:/work/sinaps/node_modules/@wagmi/core/dist/chunk-LAFZBYO7.js:398:60)
    at createConfig (file:///C:/work/sinaps/node_modules/@wagmi/core/dist/chunk-LAFZBYO7.js:636:19)
    at createConfig (file:///C:/work/sinaps/node_modules/wagmi/dist/index.js:37:18)
    at App (C:\work\sinaps\.next\server\chunks\4178.js:3517:76)
```

**Comment by JohnnyGoodpick** [comment] 2023-08-29 22:05
```
const connectors = connectorsForWallets([
		...wallets,
		{
			groupName: 'Other',
			wallets: [
				argentWallet({
					projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_API_KEY!,
					chains,
				}),
				trustWallet({
					projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_API_KEY!,
					chains,
				}),
				ledgerWallet({
					projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_API_KEY!,
					chains,
				}),
				rainbowWallet({
					projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_API_KEY!,
					chains,
				}),
				// metaMaskWallet({
				// 	projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_API_KEY!,
				// 	chains,
				// }),
				coinbaseWallet({ chains, appName: 'Sinaps' }),
				walletConnectWallet({
					projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_API_KEY!,
					chains,
				}),
			],
		},
	]);
```

Like someone mentionned in previous comment, it's related to metamask connector as commenting said lines removes the error.
So the error originate from the metaMaskWallet from '@rainbow-me/rainbowkit/wallets';

But in my case I cannot seem to be able to swap it to another library, is it planned to be fixed ?

**Comment by DanielSinclair** [comment] 2023-08-30 15:46
@JohnnyGoodpick This does seem to be upstream from RainbowKit in Wagmi which RainbowKit relies on. Can you share a minimal CodeSandbox example with your bundler and framework configuration? Would really help me diagnose!

**Comment by JohnnyGoodpick** [comment] 2023-08-31 22:00
@DanielSinclair Here is a minimal exemple, it happens at build time,
best of luck
https://codesandbox.io/p/sandbox/brave-gianmarco-gwnq9r

**Comment by DanielSinclair** [comment] 2023-09-01 04:19
The issue turned out to be because of a type mismatch in `viem/chains` versus `wagmi/chains`. You'll just want to use the `wagmi/chains` import going forward.

**Closed by DanielSinclair** 2023-09-01 04:19 UTC
