### ISSUE TITLE
[222] ConnectButton doesn't show ENS name 

### ISSUE THREAD

**Issue by d2vin** [rainbow-me/rainbowkit#385] opened 2022-05-16 02:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

^0.3.5

### Current Behavior

ConnectButton is not showing my ENS name, only my wallet address. 

### Expected Behavior

Expected to see my .eth name

### Anything else?

Just seems like the ENS service doesn't seem to be working. When I use the following wagmi hooks and then log my ensName i get null... 

`const { data: account } = useAccount(); const { data: ensName } = useEnsName({ address: account?.address });`

The feature was working initially, now when I start an entirely new app I get the same problem. Although I see the ENS feature working on the [rainbow kit docs](https://www.rainbowkit.com/docs/installation)

**Comment by jxom** [comment] 2022-05-16 02:49
`wagmi` returns `null` when there is no ENS associated with the given address. Are you sure your ENS has not been transferred to a different address? Does your ENS have a reverse record set up that points to your wallet address? You can check this by entering your wallet address [here](https://app.ens.domains/).

Please provide the ENS if you still can't figure it out.

**Comment by d2vin** [comment] 2022-05-16 03:10
Sure the ens name is d2vin.eth.

Here is the brand new next.js app I'm using that's giving me the same result. Do you think it's something to do with server side rendering? Because the ENS feature was working at first

`
// _app.js 
import "../styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import {
  apiProvider,
  configureChains,
  getDefaultWallets,
  RainbowKitProvider,
} from "@rainbow-me/rainbowkit";
import { chain, createClient, WagmiProvider } from "wagmi";

function MyApp({ Component, pageProps }) {
  const { chains, provider } = configureChains(
    [chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum],
    [apiProvider.alchemy(process.env.ALCHEMY_ID), apiProvider.fallback()]
  );

  const { connectors } = getDefaultWallets({
    appName: "My RainbowKit App",
    chains,
  });

  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
  });

  return (
    <WagmiProvider client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <Component {...pageProps} />
      </RainbowKitProvider>
    </WagmiProvider>
  );
}

export default MyApp;

// index.js
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1>
          <ConnectButton />
        </h1>
      </main>
    </div>
  );
}
`

**Comment by jxom** [comment] 2022-05-16 03:36
The wallet address `0x06B7...DA77` seems to be resolving to `d2vin.eth` fine for me on [rainbowkit.com](https://www.rainbowkit.com/).

In your example, try move the `createClient` function out of the `MyApp` component as creating the client on render could cause some funky state issues:

```diff
+...
+const wagmiClient = createClient({ ... });

function MyApp({ Component, pageProps }) {
- ...
- const wagmiClient = createClient({ ... });

  return (
    <WagmiProvider client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <Component {...pageProps} />
      </RainbowKitProvider>
    </WagmiProvider>
  )
}
```

You can also try compare your setup to our [Next.js example](https://github.com/rainbow-me/rainbowkit-examples/blob/main/with-next).

**Comment by d2vin** [comment] 2022-05-16 05:18
@jxom followed your suggestion but I'm still getting the same result. I also copied and pasted from the Next.js example you sent only to get the same result.

**Comment by jxom** [comment] 2022-05-16 05:29
Do you get the issue in [this CodeSandbox](https://codesandbox.io/s/admiring-marco-y9s29r?file=/pages/_app.tsx)? This is forked directly from our Next.js example. I can't seem to reproduce it.

<img width="611" alt="Screen Shot 2022-05-16 at 3 28 32 pm" src="https://user-images.githubusercontent.com/7336481/168525334-7a8d76ff-5dc4-4f7a-b4e5-753794ea0900.png">

**Comment by d2vin** [comment] 2022-05-16 15:59
@jxom This feature is working in the sandbox, but when I take out the typescript syntax and run it in javascript it doesn't seem to be working. Could this be the issue?

**Comment by jxom** [comment] 2022-05-16 20:15
Here is the same example using JavaScript: https://codesandbox.io/s/admiring-marco-y9s29r?file=/pages/_app.js

Can't seem to reproduce this, so going to close as I don't think this is an issue directly with RainbowKit. Feel free to [DM me on Twitter](https://twitter.com/jakemoxey) if you still can't get it working, and I'll be happy to work with you to figure out what's wrong.

**Closed by jxom** 2022-05-16 20:15 UTC

**Comment by d2vin** [comment] 2022-05-16 22:52
@jxom just started working again out of nowhere. Just gave the twitter a follow!
