### ISSUE TITLE
[bug] <Connect button state not updating after metamask disconnect>

### ISSUE THREAD

**Issue by edgardo-mkr** [rainbow-me/rainbowkit#807] opened 2022-10-10 23:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.1

### wagmi Version

0.6.8

### Current Behavior

In a certain case scenario when disconnecting from metamask it still shows my address and balance in the connect button.

### Expected Behavior

it should just show the connect wallet button 

### Steps To Reproduce

1.connect with metamask.
2.disconnect with the account modal.
3.close the web browser (in my case i used chrome).
4.open and connect again with metamask.
5.now disconnect using metamask and it will still show all the account data in the connect button.

**Comment by abartolo** [comment] 2022-10-20 02:11
I am also having this issue with RainbowKit version: **0.7.2**. It works fine after reverting to 0.5.3 since I tried every version before @latest to find the last working version.

1) Connect to wallet
2) Refresh Page - still connected to wallet(good)
3) Disconnect via Rainbowkit UI - Shows the "Connect" button since I clicked "Disconnect"
4) Refresh page - Shows connected again even tho I disconnected before.

**Comment by abartolo** [comment] 2022-10-20 18:23
After messing around with Custom wallet and walletlist I found that the issue might be the `infjectedWallet` and `metaMaskWallet`. The other wallet connections did not have this when I connect/disconnect/refresh.

```
const connectors = connectorsForWallets([
  {
    groupName: 'Recommended',
    wallets: [
      // injectedWallet({ chains }),
      alexCustomWallet({ chains }),
      // metaMaskWallet({ chains }),
      rainbowWallet({ chains }),
      walletConnectWallet({ chains }),
      coinbaseWallet({ appName: 'DeFi App', chains }),
    ],
  },
]);
```

**Comment by mathesond2** [comment] 2022-10-28 12:02
I'm having this issue as well. I've created a [Loom video recording](https://www.loom.com/share/020c680054f545298e8778e02b310c98) to illustrate this issue along with an [associated small repo](https://github.com/mathesond2/rainbowkit-issue) available for checkout. Please let me know if I can help further, happy to do so :)

**Comment by sarinniural** [comment] 2022-11-09 19:16
It happens on https://www.rainbowkit.com/ when you disconnect the wallet and refresh it, it is still connected. Have to go to metamask to disconnect.

**Comment by chrisvxd** [comment] 2022-11-18 19:26
Suspect this is because the `shimDisconnect` option from wagmi is not getting applied properly:

https://github.com/wagmi-dev/wagmi/pull/119

**Comment by harryranakl** [comment] 2022-11-28 06:28
https://github.com/rainbow-me/rainbowkit/issues/836#issuecomment-1328580794

[known issue](https://github.com/MetaMask/metamask-extension/issues/13375#issuecomment-1087023057) with MetaMask
[https://github.com/wagmi-dev/wagmi/issues/1239](https://github.com/wagmi-dev/wagmi/issues/1239)

**Comment by danielgangl** [comment] 2022-11-30 12:08
Had the same issue, was resolved with rainbow 8.x version. Sadly I still couldn't use it then because it has a few other major bugs that have yet to be resolved

**Comment by terrytjw** [comment] 2022-12-26 05:06
Has anyone managed to fix this bug yet?

**Comment by terrytjw** [comment] 2022-12-26 05:36
How about setting `autoConnect: false`?
<img width="434" alt="image" src="https://user-images.githubusercontent.com/59902670/209507207-6ccda610-72a5-492a-afc1-195c8becf6cc.png">

**Comment by jackromo888** [comment] 2022-12-26 06:02
🍍

**Comment by terrytjw** [comment] 2022-12-26 06:29
Ok so for this, whenever you refresh while it's connected, the wallet disconnects as well. So it's not really a viable solution.

**Comment by webexpert821** [comment] 2023-01-08 20:44
Yeah, Exactly @terrytjw 
To make autoConnect: false is not viable solution.
Then, is there no way to solve this trouble ?

**Comment by terrytjw** [comment] 2023-01-29 11:19
> ![2022-11-23 06 22 49](https://user-images.githubusercontent.com/1811365/203570606-8861a408-e5c8-470e-9cf8-2014c27e230b.gif) [ ![2022-11-23 06 22 49](https://user-images.githubusercontent.com/1811365/203570606-8861a408-e5c8-470e-9cf8-2014c27e230b.gif) ](https://user-images.githubusercontent.com/1811365/203570606-8861a408-e5c8-470e-9cf8-2014c27e230b.gif) [ ](https://user-images.githubusercontent.com/1811365/203570606-8861a408-e5c8-470e-9cf8-2014c27e230b.gif)

Is this issue fixed yet?

**Comment by webexpert821** [comment] 2023-01-29 15:13
Still not fixed.
Please try in here: https://www.rainbowkit.com/docs/introduction
Even in here, we can't disconnect properly...

**Comment by webexpert821** [comment] 2023-01-29 15:14
still not fixed.

**Comment by natrixofficial** [comment] 2023-01-31 06:03
This error has gone after add shimDisconnect to true. Aka: ```metaMaskWallet({ chains, shimDisconnect: true }),```
I have just tried now. Rebuild my test project. connect, then disconnect and refresh the page. After it the "Connect" button still in "Connect" state ;)
I am using the latest version of rainbowkit (0.8.1) and wagmi 0.9.6

**Comment by webexpert821** [comment] 2023-01-31 11:59
wow, great. thanks @natrixofficial

**Comment by terrytjw** [comment] 2023-02-02 13:45
> 

I'm using the <ConnectButton /> component directly. Does it work for that too?

**Comment by rjborba** [comment] 2023-02-03 12:39
This issue is related to metamask. It does not allows to change the connect state. MetamaskWallet connector on wagmi has a way to manage it by keeping track of users actions locally:

`metaMaskWallet({ chains, shimDisconnect: true })`


This issue is NOT related to Rainbowkit and should be closed.

**Closed** 2023-02-15 02:45 UTC

**Comment by Kethatril** [comment] 2023-02-16 03:56
Due to a bug in wagmi you need to make sure all of the connectors that you use that are either InjectedConnector or extend InjectedConnector have shimDisconnect set to true. For the default set of connectors that RainbowKit uses (from getDefaultWallets) those are: metaMaskWallet, injectedWallet and braveWallet.

**Comment by ajeetgill** [comment] 2023-03-01 18:17
not the best option but clearing the localstorage helps - though it should just work irrespective of if the issue is with wagmi or metamask or whatever.

**Comment by Chriton** [comment] 2023-03-15 00:26
I've fixed it like this:

`const {chains, provider} = configureChains(
    [mainnet],
    [
        alchemyProvider({apiKey: (process.env.REACT_APP_ALCHEMY_API as string), priority: 0}),
        infuraProvider({apiKey: (process.env.REACT_APP_INFURA_API as string), priority: 1}),
        publicProvider({priority: 2})
    ]
);

const connectors = connectorsForWallets([
    {
        groupName: 'Recommended',
        wallets: [
            injectedWallet({ chains, shimDisconnect: true }),
            metaMaskWallet({ chains, shimDisconnect: true }),
            coinbaseWallet({ chains, appName: 'Linagee Identity' }),
            ledgerWallet({ chains }),
            rainbowWallet({ chains, shimDisconnect: true }),
            walletConnectWallet({ chains }),
        ],
    },
    {
        groupName: 'Other',
        wallets: [
            trustWallet({ chains, shimDisconnect: true }),
        ]
    }
]);

const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider
});`

**Comment by balajipdm** [comment] 2024-05-23 06:17
The following localStorage attributes will help disconnect from the MetaMask wallet on disconnect:

```
localStorage.setItem('wagmi.io.metamask.disconnected', true)
localStorage.setItem('wagmi.metaMask.disconnected', true)
```

Hope it helps

**Comment by DanielSinclair** [comment] 2024-05-23 06:24
@balajipdm These localstorage keys are actually handled by Wagmi internally, so there shouldn't be a need to adjust them. `metaMask` would also be replaced by each individual connector id, so you'd need to handle multiple keys. There is indeed an issue with Wagmi v2 currently that seems to mix connector ids and leads to unexpected persistence, which is being investigated here, and should be fixed soon: https://github.com/wevm/wagmi/issues/3606
