### ISSUE TITLE
[bug] Verification gets stuck on using custom auth

### ISSUE THREAD

**Issue by rivaratyr** [rainbow-me/rainbowkit#1497] opened 2023-09-02 19:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues
Possibly https://github.com/rainbow-me/rainbowkit/issues/1119 is related.
Seems https://github.com/orgs/WalletConnect/discussions/3590 is related as well.

### RainbowKit Version

1.0.8

### wagmi Version

1.3.10

### Current Behavior

When implementing a custom authentication by `createAuthenticationAdapter()` from [RainbowKit](https://www.rainbowkit.com/) following the docs on https://www.rainbowkit.com/docs/custom-authentication

The message to sign (login) shows perfectly, but it freezes on the verification step window even if I return true forcibly.
<img width="337" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/97779276/97644c82-0d8a-4aa9-8bce-be92269808e2">

Based in the interface it needs a boolean:
`export interface AuthenticationAdapter<Message> {
getNonce: () => Promise<string>;
createMessage: (args: {
    nonce: string;
    address: string;
    chainId: number;
}) => Message;
getMessageBody: (args: {
    message: Message;
}) => string;
verify: (args: {
    message: Message;
    signature: string;
}) => Promise<boolean>;
signOut: () => Promise<void>;}`

What can be the issue?

### Expected Behavior

Verifying continues or provides error message.

### Steps To Reproduce

1. Implement custom authentication based on https://www.rainbowkit.com/docs/custom-authentication
2. Log in with RainbowKit
3. Verify by signing the message generated by the sample code from https://www.rainbowkit.com/docs/custom-authentication 
4. Wait for verification answer

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

Can provide git repository in private, also available for a 15-30 min call to showcase the issue.

### Anything else?

Environment is React with create-react-app, Node 18, localhost:3000. Relevant excerpt from package.json:
`"dependencies": {
    "@rainbow-me/rainbowkit": "^1.0.8",
    "axios": "^1.4.0",
    "dotenv": "^16.3.1",
    "lodash.merge": "^4.6.2",
    "react": "^18.2.0",
    "react-router": "^6.10.0",
    "react-router-dom": "^6.10.0",
    "siwe": "^2.1.4",
    "typescript": "^5.0.4",
    "viem": "^1.6.0",
    "wagmi": "^1.3.10"
  },
  "devDependencies": {
    "react-scripts": "^5.0.1"
  },
  "overrides": {
    "react-scripts": {
      "typescript": "^5"
    }
  }`

**Comment by balazsnemeth-bce** [comment] 2023-09-08 08:25
Any hints on this guys? Would be great to go to production with it.

**Comment by rivaratyr** [comment] 2023-09-08 10:21
This issue is related to https://github.com/orgs/WalletConnect/discussions/3590 as well. Seems WalletConnect is failing on calling the `AuthenticationAdapter` 's verify() function because of: 

![image](https://github.com/rainbow-me/rainbowkit/assets/97779276/c9dc8fff-06d6-4118-911b-eb5fee2f42f7)

**Comment by rivaratyr** [comment] 2023-09-08 11:18
You can move forward a bit with this if you're using create-react-app. Add custom headers to the Webpack Dev Server to be able to frame the above domain.

Install Dependencies:
`npm install react-app-rewired customize-cra --save-dev`

Create a config-overrides.js file at the root of your project. This is where you'll make changes to the Webpack configuration.
```
const { overrideDevServer } = require('customize-cra');

module.exports = {
  devServer: overrideDevServer(
    config => ({
      ...config,
      headers: {
        'Content-Security-Policy': "frame-ancestors 'self' https://example.com;"
      }
    })
  )
};
```
In your package.json, update the start, build, and test scripts to use react-app-rewired:
```
{
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test"
  }
```

Still not working sadly, however the domain https://verify.walletconnect.com finally can be reached from localhost.

**Comment by xRozzo** [comment] 2023-09-08 13:01
I encountered the same problem: it keeps verifying the signature indefinitely. I am using NextAuth, and the authorize function is never triggered. Thus, I assume the problem might be related to the configuration or packages. Recently, I built a similar system, and it worked just fine. We are merely migrating it to Next 13 with the server components.

**Comment by KoenRijpstra** [comment] 2023-09-20 09:51
@xRozzo Can you check what your NEXTAUTH_URL is? I had the same problem when I was using a different URL then I specified.

**Comment by c0mm4nd** [comment] 2023-10-04 09:11
When nextjs 13.4.9 auth works, but gets frozen on `verifying signature` after updating to 13.5.4.

Auth dependencies:
```
    "@rainbow-me/rainbowkit": "^1.0.11",
    "@rainbow-me/rainbowkit-siwe-next-auth": "0.3.0",
    "next-auth": "^4.23.2",
    "viem": "^1.14.0",
    "wagmi": "^1.4.3",
```

I see that the `/api/auth/session` request directly gets an empty json object, without executing CredentialsProvider's authorize method or any callback in authOptions.

**Comment by KosmosKey** [comment] 2024-01-03 14:58
Hey @rivaratyr. I can't reproduce this on my end. Are you able to tell me what wallet you're using when testing this ? 

Are you able to see if you're getting any console errors from your browser ?

**Comment by KosmosKey** [comment] 2024-01-21 22:34
@rivaratyr Can't seem to reproduce this on my end. Can you look at our example code [here](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-siwe-iron-session/pages/_app.tsx) and let me know if there was anything missing ? 

Also a small reproducible example would be great. Link to codesandbox or repo would be awesome.

**Comment by KosmosKey** [comment] 2024-02-03 02:49
Going to close this issue for now since can't reproduce this on my end. Refer to [this](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-siwe-next-auth) example if you wanna use next-auth 👍

**Closed** 2024-02-03 02:50 UTC
