### ISSUE TITLE
[bug] <title> Gate wallet Io connect is not found errror

### ISSUE THREAD

**Issue by yashsisodiya** [rainbow-me/rainbowkit#2114] opened 2024-07-22 10:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

Getting below issue while trying to add an wallet button for gateWallet using below code

<WalletButton wallet="gateWallet" />

Error:
Uncaught runtime errors: × ERROR Connector not found at WalletButtonRenderer (http://localhost:3000/static/js/bundle.js:514033:11) at renderWithHooks (http://localhost:3000/static/js/bundle.js:278692:22) at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:282259:24) at beginWork (http://localhost:3000/static/js/bundle.js:283978:20) at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:268948:18) at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:268992:20) at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:269049:35) at beginWork$1 (http://localhost:3000/static/js/bundle.js:288947:11) at performUnitOfWork (http://localhost:3000/static/js/bundle.js:288195:16) at workLoopSync (http://localhost:3000/static/js/bundle.js:

### Expected Behavior

It should give button for gate wallet io just like it gives for other wallet like
https://www.gate.io/web3/dapps
<WalletButton wallet="metamask" /> and so more

### Steps To Reproduce

import { WalletButton } from '@rainbow-me/rainbowkit';
<WalletButton wallet="gateWallet" />

**Comment by yashsisodiya** [comment] 2024-07-22 10:35
@magiziz  can you please look this

**Comment by GTHubDevi** [comment] 2024-07-22 11:11
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @yashsisodiya

**Comment by magiziz** [comment] 2024-07-22 13:14
@yashsisodiya Can you try the following ?

1. If you use `getDefaultConfig` you'd need to import `gateWallet` to one of your wallet group list like this.

```tsx
import { getDefaultConfig } from "@rainbow-me/rainbowkit";
import { mainnet } from "wagmi/chains";
import { gateWallet } from "@rainbow-me/rainbowkit/wallets";

export const config = getDefaultConfig({
  appName: "RainbowKit demo",
  projectId: "YOUR_PROJECT_ID",
  chains: [mainnet],
  wallets: [{ groupName: "Popular", wallets: [gateWallet] }],
  ssr: true,
});
```

2. Import `WalletButton` component and add "gate" as wallet.
```tsx
import { WalletButton } from "@rainbow-me/rainbowkit";

<WalletButton wallet="gate" />
```

**Comment by yashsisodiya** [comment] 2024-07-22 15:04
Thanks @magiziz   it worked
but it is creating issues with metamask connector
https://codesandbox.io/p/sandbox/rainbowkit-sign-887fq3

**Comment by magiziz** [comment] 2024-07-22 15:34
@yashsisodiya I see. Gate wallet is marking their wallet as "MetaMask". We can't do anything on our end since it's the Gate wallet problem that they mark their wallet as MetaMask.

<img width="816" alt="image" src="https://github.com/user-attachments/assets/df756d73-ad93-4171-9ba8-21ef83435904">

**Comment by yashsisodiya** [comment] 2024-07-23 11:48
Ok, Also the connection is quite unstable. Sometimes it connects, but we never get redirected to the application. Other times, we never receive a connection and sign request on the wallet, and so on.

**Comment by magiziz** [comment] 2024-07-23 13:07
> but we never get redirected to the application

@yashsisodiya Can you describe what you mean by that ?

> we never receive a connection and sign request on the wallet, and so on.

Is this a metamask issue or Gate wallet issue ?

**Comment by yashsisodiya** [comment] 2024-07-23 13:53
It is gate wallet issue.
Basically sometimes it gets connected but sometimes it behaves weird like on wallet it shows connected message but on our application no connection established , And also on mobile if connection established it always returns error for chain not found

**Comment by magiziz** [comment] 2024-07-23 14:39
@yashsisodiya I see what you mean. Gate wallet also behaves weird on connect modal. I think the best thing to do for now is to reach out to their support team and see what's going on since this is out of our control. We've had a few wallets that didn't behave the way that they should've behaved and it's usually their fault.

**Comment by yashsisodiya** [comment] 2024-07-24 13:54
@magiziz  On disconnect it is giving issues like showing disconnected at that time but the wallet is still connected to our application if I see it from the wallet connection list.

**Comment by yashsisodiya** [comment] 2024-07-24 14:16
Alright, here are the details:

If I don't modify my default config to add the Gate wallet connector, everything works fine. However, if I add the Gate wallet connector to my default config, the button for the Gate wallet behaves in a buggy manner. It doesn't disconnect properly, and after connecting, it doesn't show the signer.

**Comment by magiziz** [comment] 2024-07-24 17:19
@yashsisodiya Yes i'm also able to reproduce those weird behaviours. As mentioned this is a Gate wallet issue rather than RainbowKit issue since every wallet works fine.

**Comment by magiziz** [comment] 2024-07-24 20:58
I'm going to close this issue for now since it seems to be a Gate wallet extension issue rather than RainbowKit issue.

**Closed by magiziz** 2024-07-24 20:58 UTC
