### ISSUE TITLE
[bug] Connection status issue with Rabby Wallet

### ISSUE THREAD

**Issue by vvvvvv1vvvvvv** [rainbow-me/rainbowkit#2136] opened 2024-08-12 05:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.9.2

### Current Behavior

1. Connect Rabby Wallet with Rainbowkit
2. Refresh page for several times
3. Sometimes the connect status will lost

### Expected Behavior

Keep the right connect status

### Steps To Reproduce

1. Open https://rainbowkit-connect-bug-xi.vercel.app/
2. Refresh for several times, check the video below

https://github.com/user-attachments/assets/6e517345-0d6e-4a18-a3ff-e24e79c85a47

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/vvvvvv1vvvvvv/rainbowkit-connect-bug

I print the connect status in console at https://github.com/vvvvvv1vvvvvv/rainbowkit-connect-bug/blob/master/src/pages/index.tsx#L9

### Anything else?

I try to reproduce with only wagmi but can't reproduce, only reproduce with rainbowkit
https://github.com/vvvvvv1vvvvvv/wagmi-reproduce (https://wagmi-reproduce.vercel.app/) here is the wagmi reproduce repo and the issue only reproduce in production, can't reproduce in dev server.

https://github.com/wevm/wagmi/issues/4194 here is the related issue in wagmi repo

Let me know if you have any guess for the issue.

**Comment by vvvvvv1vvvvvv** [comment] 2024-08-12 06:11
btw I'm core engineer of Rabby Wallet, happy to help fix the issue if you can let me know what cause it

**Comment by magiziz** [comment] 2024-08-12 07:44
@vvvvvv1vvvvvv I'll have a look and get back you as soon as possible.

**Comment by magiziz** [comment] 2024-08-15 14:08
For some reason i'm not able to reproduce this.

https://github.com/user-attachments/assets/f1b26e2c-eed0-4f5f-adf9-4519fa4b1b2b

Can you take a look at [this](https://github.com/wevm/wagmi/blob/main/packages/core/src/connectors/injected.ts#L168-L200) Wagmi connect function and see why Rabby might block the connection ?

**Comment by vvvvvv1vvvvvv** [comment] 2024-08-16 06:56
This is quite odd. Everyone around me experiences the issue after refreshing about 10 times. Also, I don't think this is related to wagmi because the problem does not occur when I use wagmi directly. The issue only appears after I start using Rainbowkit.

**Comment by magiziz** [comment] 2024-08-16 09:08
@vvvvvv1vvvvvv Yeah this is odd. What extensions do you use when encountering the bug ?

**Comment by vvvvvv1vvvvvv** [comment] 2024-08-18 14:14
Only Rabby Wallet extension, and looks like it's fixed after I update Chrome to latest version

**Comment by magiziz** [comment] 2024-08-19 11:20
@vvvvvv1vvvvvv Interesting. Was the issue coming from Rabby wallet then ?

**Comment by DanielSinclair** [comment] 2024-08-26 06:51
Closing as this behavior seems to have resolved after a Chrome change

**Closed by DanielSinclair** 2024-08-26 06:51 UTC
