### ISSUE TITLE
While doing transaction from metamask User rejected request error thrown

### ISSUE THREAD

**Issue by Snehagupta1907** [rainbow-me/rainbowkit#2122] opened 2024-07-29 11:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.6.7

### Current Behavior

If the browser has phantom and metamask wallet then doing any transaction using metamask user rejected request error thrown but if we delete the phantom wallet from browsers everything works fine.

issue is here

this.selectExtension = ()=>jt(this, null, function*() {
var e;
if (!this.targetProvider && !this.isSelectingExtension) {
this.isSelectingExtension = !0;
try {
let t = (e = Yf.phantom) == null ? void 0 : e.ethereum;
if (t) {
if (!this.detected.length) {
this.setProvider(t),
window.dispatchEvent(new Event("ethereum#initialized"));
return
}
switch (yield t.request({
method: "wallet_selectEthereumProvider",
params: []
})) {
case "ALWAYS_USE_PHANTOM":
case "CONTINUE_WITH_PHANTOM":
{
this.setProvider(t);
break
}
case "CONTINUE_WITH_METAMASK":
case "ALWAYS_USE_METAMASK":
{
let[o] = this.detected;
for (let s of this.detected)
s.isMetaMask && this.setProvider(s);
!this.targetProvider && o && this.setProvider(o);
break
}
}
}
} catch (t) {
console.error(t)
} finally {
this.isSelectingExtension = !1
}
}

### Expected Behavior

We want that if the browser has any wallet irrespective, if we choose metamask and it get connected so transaction should proceed.

### Steps To Reproduce

Just install both metamask and phantom try to do evm transaction from metamask.

like any send transaction method for let say on polygon amoy chain ....keeping metamask and phantom wallet in the browser

### Anything else?

Use chrome browser

**Comment by Snehagupta1907** [comment] 2024-07-29 17:09
@magiziz  Can you share the version cause when i am trying to use for even send transaction this error coming
![image](https://github.com/user-attachments/assets/6d540e16-2360-455b-8fe9-a3131bdce6c4)
![image](https://github.com/user-attachments/assets/f3b62d19-955e-4151-8278-d4920ec55854)

coming from file VM of rainbowkit

**Comment by Snehagupta1907** [comment] 2024-07-29 17:11
try {
                        let t = (e = Yf.phantom) == null ? void 0 : e.ethereum;
                        if (t) {
                            if (!this.detected.length) {
                                this.setProvider(t),
                                window.dispatchEvent(new Event("ethereum#initialized"));
                                return
                            }
                            switch (yield t.request({
                                method: "wallet_selectEthereumProvider",
                                params: []
                            })) {
                            case "ALWAYS_USE_PHANTOM":
                            case "CONTINUE_WITH_PHANTOM":
                                {
                                    this.setProvider(t);
                                    break
                                }
                            case "CONTINUE_WITH_METAMASK":
                            case "ALWAYS_USE_METAMASK":
                                {
                                    let[o] = this.detected;
                                    for (let s of this.detected)
                                        s.isMetaMask && this.setProvider(s);
                                    !this.targetProvider && o && this.setProvider(o);
                                    break
                                }
                            }
                        }
                    } catch (t) {
                        console.error(t)
                    } finally {
                        this.isSelectingExtension = !1
                    }
                    
                    This complete script of that VM

**Comment by Snehagupta1907** [comment] 2024-07-29 17:19
https://streamnft-rent.vercel.app/polygon%20amoy

try lending nft on bayc polygon amoy ....if you want i can share the nft

**Comment by MatthewGreenberg** [comment] 2024-07-29 18:30
if my google chrome has both the phatom wallet and metamask extension, my application doesn't load and just crashes. Removing either one makes the app work again. Sorry if this is irrelevant to the above conversation but the interplay between those two wallets is causing me issues as well, thanks.

**Comment by Snehagupta1907** [comment] 2024-07-29 18:45
yes exactly ...if we delete one wallet it works fine but expected is that should work always irrespective of wallets in the browser

**Comment by magiziz** [comment] 2024-07-29 19:25
@Snehagupta1907 The code you provided doesn't seem to use any Wagmi hooks. Can you share a minimal reproducible example which uses Wagmi and RainbowKit ?  CodeSandbox or github repo link would be enough.

@MatthewGreenberg The app seems to work fine if i enable both extensions. You can test it here as well https://rainbowkit-example.vercel.app

<img width="742" alt="image" src="https://github.com/user-attachments/assets/6133a6f4-d74e-4464-81ef-c9ea19b0c0df">

**Comment by Snehagupta1907** [comment] 2024-07-30 08:54
code is using the wagmi hooks....and sorry i can't share the code repo as it's private

**Comment by Snehagupta1907** [comment] 2024-07-30 08:56
can you share your code for the application if possible

**Comment by Snehagupta1907** [comment] 2024-07-30 15:04
I ahve share the code snippet where it is throwing error can you please look it up ASAP

**Comment by magiziz** [comment] 2024-07-30 15:17
@Snehagupta1907 Here is the source code for the example dApp https://github.com/rainbow-me/rainbowkit/tree/main/packages/example

The code you provided is from a webpack build file and i can't see any Wagmi hooks being used. Can you share a small reproducible example which uses Wagmi and RainbowKit ?

**Comment by Snehagupta1907** [comment] 2024-07-30 16:11
![image](https://github.com/user-attachments/assets/5af622ab-444f-4ea3-af95-9837af063694)
![image](https://github.com/user-attachments/assets/cfc59552-53c8-487d-9f7e-02397e0d4f6b)
![image](https://github.com/user-attachments/assets/a48c0b33-9d1e-4ffe-ade4-ce61bbfbf90b)
![image](https://github.com/user-attachments/assets/9aefe165-5e82-4ca0-89a7-bc8483467818)


you can refer to this here clearly it is checking phantom and metamask

**Comment by Snehagupta1907** [comment] 2024-07-30 16:11
and error t is thrown...user rejected error

**Comment by Snehagupta1907** [comment] 2024-07-30 17:06
i am using ether js for contract integration

**Comment by magiziz** [comment] 2024-07-30 18:08
@Snehagupta1907 I'm not able to see that you use Wagmi here. Are you manually accessing the `window.ethereum` API without using Wagmi ?

**Comment by Snehagupta1907** [comment] 2024-07-30 18:57
i am using wagmi...idk from which module that code is coming

**Comment by magiziz** [comment] 2024-07-30 19:07
I'm going to close this issue since no minimal reproducible example was provided. Feel free to re-open this issue with a reproducible example or create a new one.

**Closed by magiziz** 2024-07-30 19:07 UTC
