### ISSUE TITLE
[bug] 0.1.2 breaks rendering on chrome mobile ios

### ISSUE THREAD

**Issue by musnit** [rainbow-me/rainbowkit#419] opened 2022-05-24 22:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.2

### wagmi Version

idk

### Current Behavior

chrome mobile on ios shows the desktop UI on [0.1.2]. it was working fine before.

### Expected Behavior

show mobile UI

### Steps To Reproduce

use rainbowkit on ios chrome mobile app - see example link below

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://spinamp-git-rainbowbugdemo-noizd.vercel.app/connect

**Comment by sashadev-sky** [comment] 2022-05-28 23:22
wanted to follow up that this is also on the latest version 0.2.1. Sort of a really big issue that I can't use this at all on any browser besides safari on my iPhone. Besides re-writing the entire modal, cannot find a fix and it's very hard to debug in Chrome because Apple does not allow you to see the console from your computer while testing for Chrome using any typical tools I would use (direct connection, browser stack, etc.)

**Comment by nickbytes** [comment] 2022-06-02 20:39
@musnit @sashadev-sky thanks for the issue description here!

I'm not currently seeing this in Chrome on iOS for either:
- [rainbowkit.com](rainbowkit.com)
- https://rainbowkit-example.vercel.app/ (deployed w/ every new change to `main`, so this is technically ahead of the latest release. Source is in the `/packages/example` folder)

This leads to me to believe it might be something to do when your custom connect button implementation. Can you think of anything in your application that may be causing this?

As of writing this, we're on 0.2.2. Can you try upgrading and see if this resolves your issue? Or could you provide code for a minimal reproducible example ?

**Comment by sashadev-sky** [comment] 2022-06-02 20:43
We can close this

**Comment by sashadev-sky** [comment] 2022-06-02 20:44
Fixed in https://github.com/rainbow-me/rainbowkit/pull/434 for reference

**Closed** 2022-06-02 20:59 UTC
