### ISSUE TITLE
[bug] Vite example on CodeSandbox is broken

### ISSUE THREAD

**Issue by nick** [rainbow-me/rainbowkit#1768] opened 2024-02-13 16:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0

### wagmi Version

2

### Current Behavior

The Vite example linked in the README is not working

**Comment by KosmosKey** [comment] 2024-02-13 19:46
@nick What exactly is broken here ? Works on my end

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/7acf214d-cc50-452f-881a-463bd8ea39e1)

Could you provide a simple reproducible example ?

**Comment by KosmosKey** [comment] 2024-02-14 12:58
@nick Here is the codesandbox [example](https://codesandbox.io/p/github/KosmosKey/rainbowkit-v2-vite/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clskr72v300063b6jfq9ufgje%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clskr72v300023b6jktt5m8ys%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clskr72v300043b6js82y1a6b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clskr72v300053b6j2jywtfpv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clskr72v300023b6jktt5m8ys%2522%253A%257B%2522id%2522%253A%2522clskr72v300023b6jktt5m8ys%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clskr72v300053b6j2jywtfpv%2522%253A%257B%2522id%2522%253A%2522clskr72v300053b6j2jywtfpv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start-app%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clslsptp7008j3b6jzpwl5zl8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clslsptp7008j3b6jzpwl5zl8%2522%257D%252C%2522clskr72v300043b6js82y1a6b%2522%253A%257B%2522id%2522%253A%2522clskr72v300043b6js82y1a6b%2522%252C%2522activeTabId%2522%253A%2522clslspq3900673b6j33l6fdxv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start-app%2522%252C%2522id%2522%253A%2522clslspq3900673b6j33l6fdxv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by KosmosKey** [comment] 2024-02-15 18:21
@nick Any updates ?

**Comment by KosmosKey** [comment] 2024-02-18 15:34
@nick Closing this issue for now since couldn't reproduce this. Please feel free to raise another issue if you have a reproducible example 👍

**Closed by KosmosKey** 2024-02-18 15:34 UTC
