### ISSUE TITLE
[bug] Wallet Connection stays at pending even when Wallet is connected

### ISSUE THREAD

**Issue by haeli05** [rainbow-me/rainbowkit#935] opened 2022-12-29 17:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.5

### Current Behavior

[](url)
![Screen Shot 2022-12-23 at 1 02 32 PM](https://user-images.githubusercontent.com/10119228/209985961-772a8f07-17f4-414e-b30f-ef332cfe543f.png)
![Screen Shot 2022-12-23 at 1 03 47 PM](https://user-images.githubusercontent.com/10119228/209985962-d86cecb6-4684-4996-9cc6-1bedbc5a0101.png)

1. Clicking connect metamask works but the screen stays at pending.
2.  Clicking Disconnect does not disconnect

### Expected Behavior

Loading screen goes away after connection. Disconnect happens when we press disconnect

**Comment by christian-miljkovic** [comment] 2023-01-18 23:39
experiencing the same: 

`@rainbow-me/rainbowkit: ^0.8.1` 
`wagmi: ^0.9.0`

**Comment by mattupham** [comment] 2023-01-19 20:54
I have the same issue:

@rainbow-me/rainbowkit: ^0.8.1
wagmi: ^0.9.0

**Comment by tomLadder** [comment] 2023-01-21 12:58
same issue :D

**Comment by DanielSinclair** [comment] 2023-02-15 03:39
This appears to be resolved with the latest Wagmi versions as I am unable to reproduce. Let me know if you're still experiencing the issue.

**Closed by DanielSinclair** 2023-02-15 03:39 UTC

**Comment by 0oooooooo0** [comment] 2024-07-22 06:57
same issue
It happened even though I had the latest version.

```
    "@rainbow-me/rainbowkit": "^2.1.3"
    "wagmi": "^2.9.2"
```
