### ISSUE TITLE
[bug] Account Info modal opens after reconnect and cannot be dismissed

### ISSUE THREAD

**Issue by rtman** [rainbow-me/rainbowkit#836] opened 2022-10-21 22:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.3

### wagmi Version

0.7.5

### Current Behavior

When the dapp is disconnected from metamask, I click the connect wallet button and follow the instructions to connect my wallet. Once it is is connected I don't see a modal popup for account info. Thats good.

If I then disconnect again (from within the dapp not from metamask) and reconnect, the account info modal pops up and I cannot close it.

### Expected Behavior

I disconnect from the connected wallet and then reconnect to see no modal popup (or if there must be one, it is closable).

### Steps To Reproduce

1. Connect a wallet using rainbow kit and metamask
2. disconnect via rainbow kit
3. Reconnect via rainbow kit
4. See that account info modal pops up and is not closable.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

I've so far been unable to reproduce this in codesandbox, still trying however.

### Anything else?

![Screen Shot 2022-10-21 at 3 30 57 PM](https://user-images.githubusercontent.com/20849135/197297892-3a4d10e1-1904-4287-a07f-995ad938d6c6.png)

**Comment by 0xAsynchronous** [comment] 2022-10-23 11:09
+1 having the same issue

**Comment by tamaka365** [comment] 2022-10-24 03:09
use `wagmi 0.6.8` or lower version

**Comment by tamaka365** [comment] 2022-10-24 03:09
use `wagmi 0.6.8` or lower version

**Comment by rtman** [comment] 2022-10-24 23:19
@tamaka365 that change actually does work, not sure why. I'd really rather not use an old version of wagmi tho. Can any contributor comment on why this is may be the case?

**Comment by mathesond2** [comment] 2022-10-25 20:44
+1 same issue

**Comment by rtman** [comment] 2022-10-25 21:15
@mathesond2 @0xAsynchronous are you able to repro this in a codesandbox? I've tried but haven't been able to yet, or at least I haven't without implementing more of our app logic.

**Comment by mathesond2** [comment] 2022-10-26 02:31
@rtman thanks for getting back to me, I've created a [Loom video recording](https://www.loom.com/share/020c680054f545298e8778e02b310c98) to illustrate this issue along with an [associated small repo](https://github.com/mathesond2/rainbowkit-issue) available for checkout. Please let me know if I can help further, happy to do so :)

**Comment by mathesond2** [comment] 2022-10-26 13:31
Just a heads up: this should also be linked with #807

**Comment by jacobedawson** [comment] 2022-10-27 10:32
+1 having this issue with rainbowkit 0.7.8

**Comment by rtman** [comment] 2022-10-28 04:02
@mathesond2 I think we're talking about two different issues here, I'm talking about is the below modal not being dismissible (cant click close) when it auto pops up on connect.

<img width="449" alt="Screen Shot 2022-10-27 at 8 57 38 PM" src="https://user-images.githubusercontent.com/20849135/198499170-f9fd7004-bb5b-4e74-a161-f3dec467584d.png">

Looks like in your loom video you're referring to the auto wallet connection as a problem. If it's a bug then it might be worth a new issue.

**Comment by rtman** [comment] 2022-10-28 04:04
@nickbytes would you mind taking a peek at this one?

**Comment by mathesond2** [comment] 2022-10-28 12:03
@rtman yep, I accidentally put this in the wrong issue, it should be in issue 807, I've added a comment there. Still, I'm seeing this issue where the modal cannot be dismissed. 👍

**Comment by 0xAsynchronous** [comment] 2022-10-28 16:04
Just a heads up, I have this issue when testing on dev/localhost but the issue magically fixes itself on prod. May be the same for you guys.

**Comment by stuckinaboot** [comment] 2022-10-29 03:45
+1 same issue

**Comment by jacobedawson** [comment] 2022-11-04 13:50
@0xAsynchronous @stuckinaboot @rtman a colleague of mine has found the cause of this issue, which is a result of this React dev mode artifact: https://stackoverflow.com/questions/72369908/why-is-useeffect-running-twice

I had a feeling it was due to a useEffect problem, and as my colleague pointed out there is an issue with <StrictMode> which is enabled only in development mode. <StrictMode> "activates additional checks and warnings for its descendants, or in other words... renders twice". I'm guessing this is causing a reset of modal state, flipping a boolean somewhere that only will close the modal when the state is "open". 

As @0xAsynchronous mentions "I have this issue when testing on dev/localhost but the issue magically fixes itself on prod". I can also confirm that the issue is not present on prod (as <StrictMode> is not running. 

To test this out, I removed the <StrictMode> component wrapping my app in index.ts (importing * as React):

![image](https://user-images.githubusercontent.com/4788506/199988043-f4ba0707-2b18-42db-9e12-43a8d31dc31c.png)

And the issue is solved! No more weird modal issues, no need to revert to older versions of wagmi, no need to delay pushing to master :)

Perhaps Rainbowkit can add this to the troubleshooting docs.

Cheers, 

Jake

**Comment by rtman** [comment] 2022-11-04 16:28
@jxom any chance we can get a rainbowkit team member to look into this?

**Comment by franzwarning** [comment] 2022-11-04 20:46
so interesting that wagmi 0.6.8 works for me too

**Comment by sarinniural** [comment] 2022-11-09 19:01
Can someone from RainbowKit team provide a official solution for this

**Comment by jxom** [comment] 2022-11-16 19:28
This should be resolved in the latest version of RainbowKit (`@rainbow-me/rainbowkit@0.8`)!

**Comment by harryranakl** [comment] 2022-11-28 06:01
[known issue](https://github.com/MetaMask/metamask-extension/issues/13375#issuecomment-1087023057) with MetaMask
[https://github.com/wagmi-dev/wagmi/issues/1239](https://github.com/wagmi-dev/wagmi/issues/1239)

**Comment by harryranakl** [comment] 2022-11-28 06:32
most probably will fix: https://github.com/rainbow-me/rainbowkit/issues/837

**Comment by slavanga** [comment] 2022-12-07 14:31
I'm using Next.js and setting `reactStrictMode: false` in `next.config.js` worked for me as a quick fix.

**Comment by petdud** [comment] 2022-12-10 16:22
+1 on this. Production works fine and as @slavanga and other mentioned, the issue is connected with the `reactStrictMode`. Setting it to `false` in `next.config.js` fixed my issue for Next app

**Comment by rtman** [comment] 2023-01-05 18:41
@petdud disabling strict mode is not a solution.

**Comment by krisgrm** [comment] 2023-01-05 22:35
currently facing this problem, I'd rather not disable `reactStrictMode`

**Comment by salvinoarmati** [comment] 2023-01-10 05:15
facing the same issue as well 🫠

**Comment by CuriouslyCory** [comment] 2023-01-10 19:50
> currently facing this problem, I'd rather not disable `reactStrictMode`

100% There's at least a handful of reasons why disabling strict mode is not recommended. I hope we can get a fix for this soon.

**Comment by mateodaza** [comment] 2023-01-14 02:30
> > currently facing this problem, I'd rather not disable `reactStrictMode`
> 
> 100% There's at least a handful of reasons why disabling strict mode is not recommended. I hope we can get a fix for this soon.

yup, commenting here to keep updated

**Comment by mastmaster** [comment] 2023-01-17 18:39
Same for me

**Comment by CamiloRX777** [comment] 2023-01-27 20:19
+1 same issue

**Comment by saqlain1020** [comment] 2023-01-30 06:51
Just disable Strict mode in react and it will work in development.
In Production Strict mode is disabled by default so you don't have to worry about this issue.

**Comment by krisgrm** [comment] 2023-01-30 12:24
I think strict mode is there for a reason.... maybe someone could try to enable strict mode only for the app below the rainbowkit provider ? 

so let the wagmi and rainbowkit work in "unsafe" mode and then rest of the app in strict mode
https://reactjs.org/docs/strict-mode.html#:~:text=You%20can%20enable%20strict%20mode%20for%20any%20part%20of%20your%20application.%20For%20example%3A

**Comment by saqlain1020** [comment] 2023-01-30 13:07
> I think strict mode is there for a reason.... maybe someone could try to enable strict mode only for the app below the rainbowkit provider ?
> 
> so let the wagmi and rainbowkit work in "unsafe" mode and then rest of the app in strict mode https://reactjs.org/docs/strict-mode.html#:~:text=You%20can%20enable%20strict%20mode%20for%20any%20part%20of%20your%20application.%20For%20example%3A

That's a nice idea.

### index.ts
```

const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            refetchOnWindowFocus: false,
        },
    },
});
const root = ReactDOM.createRoot(document.getElementById("root")!);

root.render(
        <WagmiConfig client={wagmiClient}>
            <RainbowKitProvider
                chains={chains}
            >
                <React.StrictMode>
                    <NotificationsProvider>
                        <App />
                        <Notifications />
                    </NotificationsProvider>
                </React.StrictMode>
            </RainbowKitProvider>
        </WagmiConfig>
);
````

Using Rainbowkit like this fixes the issue.

**Comment by DanielSinclair** [comment] 2023-02-15 03:33
This should now be resolved with the latest RainbowKit and Wagmi versions. Will reopen if this issues persists.

**Closed by DanielSinclair** 2023-02-15 03:33 UTC

**Comment by aditya172926** [comment] 2023-02-15 06:57
I am using `"@rainbow-me/rainbowkit": "^0.9.0"` and `"wagmi": "^0.9.6"` in NextJS.
This issue is still persisting in that.

**Comment by DanielSinclair** [comment] 2023-02-15 15:00
Hi @aditya172926. Please bump up to Wagmi 0.11.x

**Comment by aditya172926** [comment] 2023-02-16 05:18
> Hi @aditya172926. Please bump up to Wagmi 0.11.x

Great! It works 👍

**Comment by aditya172926** [comment] 2023-06-28 20:55
> I am using "wagmi": "^1.2.0", "@rainbow-me/rainbowkit": "^1.0.1" in React. This issue is still persisting. Even Disabling the strict mode in React didn't solve the issue for me.

Getting the wagmi 0.11.x version worked for me. I even bumped the rainbow kit to its latest version. I recommend you check your package lock file in react project to see what exact versions of wagmi and rainbow are installed. @developOleg250
