### ISSUE TITLE
[bug] Custom wallet group not functioning in the new beta release

### ISSUE THREAD

**Issue by SyedAhkam** [rainbow-me/rainbowkit#1701] opened 2024-01-12 19:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0-beta.0

### wagmi Version

2.1.2

### Current Behavior

<img width="592" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/52673095/9958d867-5afe-4688-b8ed-832b8f14e7bb">

### Expected Behavior

Expected it to create a new wallet group in the 'connect wallet' popup named "Recommended" with a single preset wallet, ie. OKX wallet.

### Steps To Reproduce

1. Create wagmi config using the `getDefaultConfig` function and create a wallet group.

```ts
const { wallets } = getDefaultWallets();

export const wagmiConfig = getDefaultConfig({
  appName: env.NEXT_PUBLIC_WC_PROJECT_NAME,
  projectId: env.NEXT_PUBLIC_WC_PROJECT_ID,
  chains: [polygonMumbai],
  wallets: [
    ...wallets,
    {
      groupName: "Recommended",
      wallets: [
        okxWallet
      ],
    },
  ],
})
```

2. Click connect wallet on web app

### Anything else?

Really appreciate the work on wagmi v2 support!

Additionally as seen in the image, a locale entry seems to be missing as well for the string "Installed".

**Comment by KosmosKey** [comment] 2024-01-12 22:47
@SyedAhkam This is an expected behaviour. OKX wallet supports EIP6963. If we detect that an EIP6963 wallet we remove that same wallet you specified in the wallet list group. 

The reason we do this is because it will be easier for the dApp to connect and manage wallets. There won't be any overridden bugs which usually happens if we don't support EIP6963 overrides.

Regarding the "Installed" missing that's expected. We haven't added localization support for that. It'll be fixed soon 🙏

**Comment by DanielSinclair** [comment] 2024-01-12 23:29
@SyedAhkam The missing string will be fixed in `2.0.0-beta.1` shortly.

**Closed** 2024-01-12 23:28 UTC

**Comment by SyedAhkam** [comment] 2024-01-13 01:02
> @SyedAhkam This is an expected behaviour. OKX wallet supports EIP6963. If we detect an EIP6963 wallet we remove that same wallet you specified in the wallet list group.
> 
> The reason we do this is because it will be easier for the dApp to connect and manage wallets. There won't be any overridden bugs which usually happens if we don't support EIP6963 overrides.

I understand the intent. However as it used to work fine in v1, but fails to in v2 -- we could call this a regression.

Now perhaps:

1. You could add a way to override that EIP6963 wallet detection.
2.  or IMO The regression / breaking change should be mentioned in the new upcoming docs.

**Comment by KosmosKey** [comment] 2024-01-13 02:52
@SyedAhkam Yeah we will mention this in the upcoming docs once we merge `beta` into `main` branch. It'll be shown in the [custom wallet list](https://www.rainbowkit.com/docs/custom-wallet-list).

**Comment by DanielSinclair** [comment] 2024-01-13 04:47
@SyedAhkam To clarify, the wallet you added is still available, it is just moved to an `Installed` list at the top, because it is detected as installed by the new EIP-6963 connection standard. This is how Wagmi v2 and other libraries will work going forward, so that dApps won't always need to include wallet connectors; every installed wallet will just appear under `Installed`. If you add more wallets to your `Recommended` section in your example, or disable the OKX wallet or visit on mobile, those wallets will continue appear.
