### ISSUE TITLE
[bug] Error: To use QR modal, please install @walletconnect/modal package

### ISSUE THREAD

**Issue by ian-os** [rainbow-me/rainbowkit#1648] opened 2023-12-08 00:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.0

### wagmi Version

1.4.10

### Current Behavior

Wallet Connect is broken when use vite(st).

When using viest (only), view tests will fail with the following:

```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
  Error: To use QR modal, please install @walletconnect/modal package
   ❯ I.initialize ../../node_modules/.pnpm/@walletconnect+ethereum-provider@2.10.2_@walletconnect+modal@2.6.2/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:7369
   ❯ processTicksAndRejections node:internal/process/task_queues:95:5
   ❯ Function.init ../../node_modules/.pnpm/@walletconnect+ethereum-provider@2.10.2_@walletconnect+modal@2.6.2/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:2743
   ❯ WalletConnectConnector.initProvider_fn ../../node_modules/.pnpm/@wagmi+connectors@3.1.5_@types+react@18.2.37_react@18.2.0_typescript@5.2.2_viem@1.18.9/node_modules/@wagmi/connectors/dist/walletConnect.js:235:35
```

Note - this is not a problem when using nextjs, this is only a problem when using vite to test.

### Expected Behavior

It's expected that Rainbowkit not throw an error.

### Anything else?

This dependency issue was fixed 2 weeks ago in the WalletConnect modal, Rainbowkit needs to have dependencies updated and patch bump.

Original issue: https://github.com/WalletConnect/walletconnect-monorepo/issues/3852
PR Fix: https://github.com/WalletConnect/walletconnect-monorepo/pull/3891

**Comment by DanielSinclair** [comment] 2023-12-11 22:22
@ian-os Do you have a reproduction example? We use `vitest` and `vite` without issue. It is possible this error is related to a recent version of Wagmi or WalletConnect.

**Comment by DanielSinclair** [comment] 2023-12-22 16:41
Closing. If you are still seeing this issue with a recent version of RainbowKit, Wagmi, or Vite, please let me know!

**Closed by DanielSinclair** 2023-12-22 16:41 UTC

**Comment by GMGNAI** [comment] 2024-02-21 10:55
我面临着同样的问题。我正在使用具有以下包详细信息的 Next.js React 项目：

```js
"@rainbow-me/rainbowkit": "2.0.0",
"viem": "^2.7.3",
"wagmi": "^2.5.5"
```

**Comment by DanielSinclair** [comment] 2024-02-21 18:00
@GMGNAI Do you have a reproducible example? This issue is likely related to a bundler issue in your configuration.

**Comment by zoheb391** [comment] 2024-03-22 14:47
hi @DanielSinclair. I'm having this same issue. I use pnpm in a monorepo setup. 

```ts
"@rainbow-me/rainbowkit": "^2.0.2",
"viem": "^2.7.12",
"wagmi": "^2.5.7",
```

**Comment by DanielSinclair** [comment] 2024-03-23 03:57
@zoheb391 Do you have a reproducible example I can look at? The issue is likely in the bundler configuration.
