### ISSUE TITLE
[bug] MetaMask Mobile: WalletConnect v2 is not working on iOS

### ISSUE THREAD

**Issue by yeshealer** [rainbow-me/rainbowkit#1303] opened 2023-06-18 19:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.4

### wagmi Version

0.12.6

### Current Behavior

https://github.com/rainbow-me/rainbowkit/assets/88679102/6ef3313a-484c-44ea-92d4-663c83435cef

https://github.com/rainbow-me/rainbowkit/assets/88679102/fda274a5-cf30-4bcc-91c6-dac49663dbdd

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://feta-models.vercel.app

**Comment by adrianotadao** [comment] 2023-06-22 21:22
@yeshealer this is working well on rainbowkit 1.0.1

**Comment by eth0izzle** [comment] 2023-06-27 09:15
Also having the same issue. @yeshealer what versions of RainbowKit, WAGMI, etc are you using? And what does your code look like?

**Comment by yeshealer** [comment] 2023-06-27 09:24
I'm using @***@***.*** and ***@***.*** on ***@***.***

// ** wagmi imports
import { getDefaultWallets, RainbowKitProvider, ConnectButton, lightTheme }
from ***@***.***/rainbowkit';
import { useAccount, configureChains, createClient, WagmiConfig, useNetwork
} from 'wagmi';
import { polygonMumbai, avalancheFuji } from 'wagmi/chains';
import { alchemyProvider } from ***@***.***/core/providers/alchemy'
import { publicProvider } from ***@***.***/core/providers/public'

const sepolia = {
    id: 11155111,
    name: 'Sepolia',
    network: 'sepolia',
    nativeCurrency: {
        decimals: 18,
        name: 'Sepolia',
        symbol: 'ETH'
    },
    rpcUrls: {
        public: { http: ['
https://ethereum-sepolia.blockpi.network/v1/rpc/public    '] },
        default: { http: ['https://rpc2.sepolia.org'] },
    },
    blockExplorers: {
        etherscan: { name: 'Sepolia', url: 'https://sepolia.etherscan.io/'
},
        default: { name: 'Sepolia', url: 'https://sepolia.etherscan.io/' },
    },
    contracts: {
        multicall3: {
            address: '0xca11bde05977b3631167028862be2a173976ca11',
            blockCreated: 11_907_934,
        },
    },
}

const { chains, provider } = configureChains(
    [avalancheFuji, sepolia, polygonMumbai],
    [
        alchemyProvider({ apiKey: 'Y4RO5waXb2A92F2h8YaQs_EduUoB5E50',
weight: 1 }),
        publicProvider({ weight: 2 })
    ]
);

const { connectors } = getDefaultWallets({
    appName: 'My RainbowKit App',
    projectId: 'bc594665ad42a77e06d48aa5d82d1a91',
    chains
});

const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider
})
function App() {
...
    return (
        <WagmiConfig client={wagmiClient}>
            <RainbowKitProvider chains={chains} theme={merge(lightTheme({
                borderRadius: 'small'
            }),
                {
                    fonts: {
                        body: 'Bruno',
                    }
                }
            )}>
                <Routes>
// ** There are routes here
                </Routes>
            </RainbowKitProvider>
        </WagmiConfig>
    );
}

My code looks like above...

**Comment by intergalacticspacehighway** [comment] 2023-06-27 16:32
We're facing same issue. I think it started happening with the latest Metamask 7.0.1. Connecting with rainbowkit on [rainbowkit's site](https://www.rainbowkit.com/) doesn't work with Metamask as well. The issue is reproducible with Rainbowkit 1.0.3.

**Comment by adrianotadao** [comment] 2023-06-27 16:37
> We're facing same issue. I think it started happening with the latest Metamask 7.0.1. Connecting with rainbowkit on [rainbowkit's site](https://www.rainbowkit.com/) doesn't work with Metamask as well. The issue is reproducible with Rainbowkit 1.0.3.

check this out https://github.com/rainbow-me/rainbowkit/issues/1262#issuecomment-1601598463 we need metamask team to fix it. 😢

**Comment by DanielSinclair** [comment] 2023-07-07 00:17
[0.12.17](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.12.17) and [1.0.5](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.0.5) are now available with a fix for this MetaMask issue.

**Closed by DanielSinclair** 2023-07-07 00:17 UTC
Labels: walletconnect

**Comment by yeshealer** [comment] 2023-07-07 02:34
thanks
