### ISSUE TITLE
[bug] redirected to https://rnbwappdotcom.app.link/SJOyoHO3Gob

### ISSUE THREAD

**Issue by axeldelafosse** [rainbow-me/rainbowkit#522] opened 2022-06-21 17:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

latest

### wagmi Version

latest

### Current Behavior

I'm redirected to https://rnbwappdotcom.app.link/SJOyoHO3Gob instead of the correct deep link on Safari iOS.

### Expected Behavior

I should be redirected to the Rainbow app.

### Steps To Reproduce

Go to https://showtime.xyz on Safari iOS and try to sign in.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/showtime-xyz/showtime-frontend

**Comment by markdalgleish** [comment] 2022-06-22 22:56
Is this a duplicate of https://github.com/rainbow-me/rainbowkit/issues/521? I'm seeing the same behaviour in the video posted there.

**Comment by nickbytes** [comment] 2022-06-24 20:51
Going to close this since seems like a duplicate.

**Closed by nickbytes** 2022-06-24 20:51 UTC
