### ISSUE TITLE
[bug] Coinbase Wallet connection redirects fail on Chrome iOS

### ISSUE THREAD

**Issue by DanielSinclair** [rainbow-me/rainbowkit#2106] opened 2024-07-18 05:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.9.2

### Current Behavior

Coinbase Wallet redirects seem to be unreliable in some mobile WebKit browsers, including Chrome for iOS

### Steps To Reproduce

1. Visit dApp in Chrome for iOS
2. Connect with Coinbase Wallet
3. Follow redirect and choose Already have a wallet
4. Deep link or universal link redirect fails, tab closes. No console logs reporter

**Comment by Samuele458** [comment] 2024-07-18 07:56
I'm experiencing the same problem, from Chrome/Safari.

**Comment by spencerstock** [comment] 2024-07-18 17:47
@DanielSinclair @Samuele458 

Do you have an environment I can use for testing? Either your dapps/applications or a sandbox, anything is great.

Pretty likely it is an issue on our side, looking into it.

**Comment by DanielSinclair** [comment] 2024-07-18 19:16
@spencerstock Yes, you can use our example dApp at https://rainbowkit-example.vercel.app/

**Comment by spencerstock** [comment] 2024-07-18 20:44
@DanielSinclair I'm currently unable to repro, if you're able to hop into a meet with me - https://meet.google.com/rpu-bqto-avr

I'll hold this meet open for an hour if you happen to be available

Other things to that will help us isolate the issue:
Does the issue persist in an incognito tab?

**Comment by spencerstock** [comment] 2024-07-19 18:59
I still haven't been able to repro, but I have seen other repro's of this problem. Working on a fix in the keys.coinbase.com popup that should get this sorted out. (we've tried other approaches but it's still not all the way solved)

**Comment by magiziz** [comment] 2024-08-05 16:01
Closing this issue since it seems like it no longer can be reproduced.

**Closed by magiziz** 2024-08-05 16:01 UTC
