### ISSUE TITLE
Not able to switch the network in Trust wallet browser in mobile !

### ISSUE THREAD

**Issue by PearlSharma** [rainbow-me/rainbowkit#1785] opened 2024-02-21 06:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0

### wagmi Version

2.0.0

### Current Behavior

I have opened my site in Trust wallet internal browser in mobile. 
I am trying to switch to other chains. 
But, every time, I am selecting other chain from the switch chain modal, nothing happens. 
Tried 3-4 times. 

### Expected Behavior

User should be able to switch to other chains. 

### Steps To Reproduce

I have opened my site in Trust wallet internal browser in mobile. 
I am trying to switch to other chains. 
But, every time, I am selecting other chain from the switch chain modal, nothing happens. 
Tried 3-4 times. 

### Anything else?

https://github.com/rainbow-me/rainbowkit/assets/96103403/176d3277-d2b1-4554-a573-f66f2f649b49

**Comment by KosmosKey** [comment] 2024-02-21 20:40
@PearlSharma I just tried to reproduce your issue and for me the trust wallet in app browser works fine with chain switching. Can you try do it in [here](https://rainbowkit-example.vercel.app/) as well ?

Also can you provide your configuration setup for RainbowKit and wagmi ?

**Comment by PearlSharma** [comment] 2024-02-22 04:18
It’s 2.0.0 latest version.

**Comment by KosmosKey** [comment] 2024-02-22 14:33
@PearlSharma Seems to be working on my end. Can you provide a small reproducible example ?

https://github.com/rainbow-me/rainbowkit/assets/53529533/fa4aa3a4-07ea-476a-8ca9-7cab68cef839

**Comment by KosmosKey** [comment] 2024-02-23 12:29
@PearlSharma Does it work for you in https://www.rainbowkit.com/ ? If it does then it seems like their project has some issues with projectId probably. Is that your project ?

**Comment by KosmosKey** [comment] 2024-02-26 13:59
@PearlSharma Any updates ?

**Comment by KosmosKey** [comment] 2024-02-27 12:07
Closing this issue for now since it's unknown what is going on and can't be reproduced on my end. Feel free to open a new issue if you're still facing this problem with a reproducible example 🙏

**Closed by KosmosKey** 2024-02-27 12:07 UTC
