### ISSUE TITLE
[bug] QRCode not showing up

### ISSUE THREAD

**Issue by mikelxc** [rainbow-me/rainbowkit#722] opened 2022-09-08 02:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.1

### wagmi Version

0.6.4

### Current Behavior

Popup works, Metamask connects without problem, but no QR code for wallet connect and wallet link.
<img width="1728" alt="Screen Shot 2022-09-07 at 10 06 12 PM" src="https://user-images.githubusercontent.com/20431963/189017505-c9d3170b-f0b6-4c83-937c-97c433bce120.png">
<img width="1728" alt="Screen Shot 2022-09-07 at 10 06 27 PM" src="https://user-images.githubusercontent.com/20431963/189017536-a9f5ad61-c81f-4c90-af6b-e68c526da9dc.png">

### Expected Behavior

QR code showing up when selected

### Steps To Reproduce

Used with a react wrapper in astro, with both client:load and client:only="react"

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://lensmo-fe.vercel.app/

**Comment by markdalgleish** [comment] 2022-09-08 23:14
Are you able to share source code for a minimal repro?

With the link you provided, I'm not seeing any errors in the console, but historically I've seen issues like this caused by missing polyfills that WalletConnect and Coinbase Wallet SDK rely on. For example, here's how we patch it in Vite: https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-vite/src/polyfills.ts

**Comment by mikelxc** [comment] 2022-09-09 04:49
> Are you able to share source code for a minimal repro?
> 
> With the link you provided, I'm not seeing any errors in the console, but historically I've seen issues like this caused by missing polyfills that WalletConnect and Coinbase Wallet SDK rely on. For example, here's how we patch it in Vite: https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-vite/src/polyfills.ts

Thank you so much for your reminder! Turns out it's indeed the polyfill causing the problem. You cannot import polyfill in an astro file. Created an example with astro create.

**Comment by markdalgleish** [comment] 2022-09-20 23:01
Closing this as it seems to be resolved. Thanks for helping to add an example!

**Closed by markdalgleish** 2022-09-20 23:01 UTC
