### ISSUE TITLE
[bug] `useMainnetEnsName` no longer checks if `mainnet` is enabled

### ISSUE THREAD

**Issue by goksu** [rainbow-me/rainbowkit#1813] opened 2024-02-29 18:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

Getting hard throws when `mainnet` is not part of the configured chains when trying to load Account Modal.

### Expected Behavior

Should not throw if `mainnet` is not configured.

### Steps To Reproduce

- Start a project with latest RainbowKit
- Configure chains as `[base, zora]` and omit `[mainnet]`
- Connect a wallet

### Anything else?

Looking at what might have changed recently on the package —

`useMainnetEnsName` is no longer checking whether or not `mainnet` is enabled as a configured chain. This specific check was introduced at https://github.com/rainbow-me/rainbowkit/commit/fd08aa1f9929269c04aad7636bf9c2417d7dfe78 to resolve issues when Ens name was being fetched for `AccountModal` even when `mainnet` is not configured. This was reverted with https://github.com/rainbow-me/rainbowkit/commit/aa0269e49655da2638fda0c6853a746d55020878. Resulting in hard crashes.

```
ChainNotConfiguredError: Chain not configured.
```

Not sure if this was done since Wagmi should be handling this case, or if there is additional config needed on our end to bypass, or it is expected to work as is and its a client implementation error.

**Comment by KosmosKey** [comment] 2024-02-29 19:57
@goksu How did you reproduce this issue ?


https://github.com/rainbow-me/rainbowkit/assets/53529533/c731e528-187d-48a5-8bbc-f2d12f047004

**Comment by goksu** [comment] 2024-02-29 20:04
> @goksu How did you reproduce this issue ?

I am working on to get it fail deterministically with an isolated environment but on CodeSandbox I was able to get it trigger if you added `mainnet` as a wallet config, connect a wallet, and remove `mainnet` and refresh. Do wonder if there is something going on with local caches.

**Comment by KosmosKey** [comment] 2024-02-29 20:32
@goksu Just got a PR opened for this, but i still can't reproduce this. 

I see that wagmi has this check when doing `getClient` for their queries [here](https://github.com/wevm/wagmi/blob/4ba761df16ceaa4746ccb0705ea8e514630b1c1b/packages/core/src/createConfig.ts#L126)

**Comment by goksu** [comment] 2024-02-29 20:45
> @goksu Just got a PR opened for this, but i still can't reproduce this.
> 
> I see that wagmi has this check when doing `getClient` for their queries [here](https://github.com/wevm/wagmi/blob/4ba761df16ceaa4746ccb0705ea8e514630b1c1b/packages/core/src/createConfig.ts#L126)

Understand this is hard to demonstrate on generic examples and my apologies for not being able to get you a deterministic way to reproduce.

Likely there is still some chance of this being due to our implementation and not RainbowKit.

I think your PR change still makes sense to me, and seems like would be right to have it but up to you to make the final call. I am going to ahead and continue to find some deterministic way to re-pro this. If not by tomorrow — I'll close the issue. 

Appreciate you looking into it!

**Comment by KosmosKey** [comment] 2024-02-29 23:50
@goksu Sounds good. Let's keep this issue open until the PR is merged. Just a quick question tho. Did the error make the app crash or just show up in screen and console ?

**Comment by KosmosKey** [comment] 2024-03-01 16:34
@goksu After you answer the question above 👆 can you also send a quick screenshot of how the error looks like ? I can't reproduce this on code sandbox as well.

**Closed** 2024-03-07 17:19 UTC
