### ISSUE TITLE
[bug] Implementation with react Js not working for mobile browsers, (native apps)

### ISSUE THREAD

**Issue by SolutionPr** [rainbow-me/rainbowkit#1487] opened 2023-08-28 16:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.8

### wagmi Version

1.3.2

### Current Behavior

Rainbow kit implementation using ReactJS is working fine on desktop, but when run using mobile its halts and takes long time to respond, opens up MetaMask but doesn't prompt for connecting wallet.

### Expected Behavior

It should work flowless on mobile, as its works on desktop, and it should enable user to connect wallet using mobile.

### Steps To Reproduce

use this link in mobile browser: 
http://52.7.25.18:3000/?amount=0.001&receiver_address=<anywalletaddess>
- Click on connect wallet,
- Choose metamask
- It will take time to respond.
- Metamask will popup but doesn't show any prompt to make connection.

**Comment by DanielSinclair** [comment] 2023-08-29 02:53
@SolutionPr Did you create and supply a new `projectId`? This sounds like a quiet WalletConnect v2 failure. Please reference this [guide](https://www.rainbowkit.com/docs/installation#configure) for information about WalletConnect v2. If that is not the case, can you share more about your test path? Are you using a mobile browser or the embedded browser inside the MetaMask app?

**Comment by SolutionPr** [comment] 2023-08-29 09:45
Yes I did and works well on Desktop, but fails with mobile, I'm using mobile browser.

**Comment by DanielSinclair** [comment] 2023-08-30 02:36
@SolutionPr Can you share a CodeSandbox or a deployment example?

**Comment by SergioArrighi** [comment] 2023-10-02 07:42
Hello guys,
first of all thanks for the terrific job.
I think I'm experiencing this same issue.
I can connect using metamask just fine using desktop browser, but when I try from my phone (Chrome mobile) I can't.
Here's what happens:
1) I click connect
2) The drawer comes up from the bottom
3) I select MetaMask
4) MetaMask correctly shows up
5) No connection prompt in MetaMask

So error should be in step number 5.

Expected behaviour:
Once MetaMask is open, a connection drawer comes up, I can click on the connect button and I get redirected to browser view.

Versions:
React 18.2.0
Rainbowkit 1.0.11
Wagmi 1.4.2
Viem 1.10.7

I will try to build a minimal project for reproducing the issue, but my guess is that any react app would do.

Thanks and best regards

**Comment by DanielSinclair** [comment] 2023-11-02 13:02
Tested against Next.js and Create React App with the latest versions of RainbowKit, Wagmi, and MetaMask on iOS in both the Mobile Safari browser and embedded dApp browser, and was unable to replicate the issue. It is likely that this was an issue on the MetaMask side that has since been resolved. Closing as a possible duplicate of #1436; will investigate Android specific behavior further.

**Closed by DanielSinclair** 2023-11-02 13:02 UTC
