### ISSUE TITLE
Connecting on mobile v2

### ISSUE THREAD

**Issue by weber77** [rainbow-me/rainbowkit#2058] opened 2024-06-18 20:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^2.1.2

### wagmi Version

^2.10.2

### Current Behavior

when I connect on mobile it opens in metamask but does prompt for connection 

https://github.com/rainbow-me/rainbowkit/assets/44323398/5a22f4cd-3be0-46e1-b898-5588e05059eb

### Expected Behavior

https://github.com/coder/coder/assets/44323398/04f86d3c-45fe-4358-a213-29f7639652ca

### Steps To Reproduce

1. follow link on a mobile browser: 
2. click `connect wallet`
3. select metamask or walletconnect
4. it opens in metamask but does prompt to confirm

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

[CodeSandBox](https://codesandbox.io/p/github/weber77/wagmi-mobile-test/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxkuudcl00063b6i8mc3fe1c%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxkuudcl00023b6ik6q302bh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxkuudcl00043b6i4u80qf7t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxkuudcl00053b6i6n9lm7hb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxkuudcl00023b6ik6q302bh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxkuudcl00013b6i4xauwesj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxkuudcl00023b6ik6q302bh%2522%252C%2522activeTabId%2522%253A%2522clxkuudcl00013b6i4xauwesj%2522%257D%252C%2522clxkuudcl00053b6i6n9lm7hb%2522%253A%257B%2522id%2522%253A%2522clxkuudcl00053b6i6n9lm7hb%2522%252C%2522activeTabId%2522%253A%2522clxkv3ggi00563b6ifdv56isb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clxkuude500083b6iycdjr2fr%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxkv3ggi00563b6ifdv56isb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxkuudcl00043b6i4u80qf7t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxkuudcl00033b6iwjgng7ms%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxkuueb40010dki8bhm5g5mu%2522%257D%255D%252C%2522id%2522%253A%2522clxkuudcl00043b6i4u80qf7t%2522%252C%2522activeTabId%2522%253A%2522clxkuudcl00033b6iwjgng7ms%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by magiziz** [comment] 2024-06-19 11:14
@weber77 Seems to be a WalletConnect issue. Can you check if you've added your preview link to the "Allowed Domains" section in the WalletConnect dashboard ?

<img width="712" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/53529533/b789abb9-f149-461a-807c-6441225bb298">

**Comment by sniper365** [comment] 2024-06-21 19:46
> @weber77 Seems to be a WalletConnect issue. Can you check if you've added your preview link to the "Allowed Domains" section in the WalletConnect dashboard ?
> 
> <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/53529533/341046310-b789abb9-f149-461a-807c-6441225bb298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5OTkyNDAsIm5iZiI6MTcxODk5ODk0MCwicGF0aCI6Ii81MzUyOTUzMy8zNDEwNDYzMTAtYjc4OWFiYjktZjE0OS00NjFhLTgwN2MtNjQ0MTIyNWJiMjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE5NDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZWM1NDExY2I5YWZkOTIxMTEwZWM1MDllYzFjMTE1NzNiMWYwYzk4N2U3ODg5NzkxNDVhNDJhN2U3ZDczYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fDag6DSQ4a1jc6-MrOM80P6OVpitPABFVc-xDncgC00">

Hey @weber77 It's working after allow domain. But new issue. When i click button that call metamask action, No action at metamask. Need another configuration?

**Comment by HemangVora** [comment] 2024-06-21 20:52
same with me no action at MM

**Comment by magiziz** [comment] 2024-06-22 01:12
@sniper365 Are you saying that whenever you try to connect with MetaMask it doesn't do anything or it's not prompting you to connect to the dApp ? Are you able to show any console errors ?

**Comment by weber77** [comment] 2024-06-24 15:15
@magiziz https://github.com/weber77/wagmi-mobile-test

**Comment by magiziz** [comment] 2024-06-25 14:56
@weber77 Seems to work for me since i use my own `projectId`. What happens if you use the `projectId` below ? https://github.com/rainbow-me/rainbowkit/blob/cdcaa25d66b522119852502f71c8efc02b1abdd9/packages/rainbowkit/src/wallets/getWalletConnectConnector.ts#L95

Don't use that in production, i'm just trying to see if you have configured everything in WalletConnect dashboard.

Also are you using any VPN's ?

**Comment by sniper365** [comment] 2024-06-25 14:58
Yes, I use VPN. that would have some issue?

**Comment by weber77** [comment] 2024-06-25 15:08
> @weber77 Seems to work for me since i use my own `projectId`. What happens if you use the `projectId` below ? https://github.com/rainbow-me/rainbowkit/blob/cdcaa25d66b522119852502f71c8efc02b1abdd9/packages/rainbowkit/src/wallets/getWalletConnectConnector.ts#L95
> 
> Don't use that in production, i'm just trying to see if you have configured everything in WalletConnect dashboard.
> 
> Also are you using any VPN's ?
> 
> 

I used it but it still doesn't work. Here's the [repo](https://github.com/weber77/wagmi-mobile-test)

https://github.com/rainbow-me/rainbowkit/assets/44323398/ae033559-ad2e-444f-8566-93b565b30718

**Comment by sniper365** [comment] 2024-06-25 15:27
I followed [wagmi ssr guide](https://wagmi.sh/react/guides/ssr)
The issue is not on wallet connect. On the desktop, third party api hook shows correctly the balance, But on the mobile it doesn't work. 

e.g
`const {  availableBalance, availableWithdraw } = useWithdraw();`
It's working on desktop but not on the mobile. any further configuration, you think?

**Comment by sniper365** [comment] 2024-06-25 15:56
> @sniper365 The reason this might be a WalletConnect issue is because you're not being deep linked correctly into the MetaMask app and we use WalletConnect to initiate the deep links.
> 
> You also mentioned that you use VPN ? Can you describe more where the VPN is pointed at ?
> 
> Also can you show the console errors you get once trying to connect with MetaMask ?
VPN location: Germany

**Comment by magiziz** [comment] 2024-06-27 10:51
@sniper365 Are you able to fully turn off your VPN and try again ? Make sure to first disconnect in MetaMask and try again using this project id `21fef48091f12692cad574a6f7753643`.

Also it would be helpful if you can share any console errors you get on mobile. You can use any android simulators for that.

**Comment by weber77** [comment] 2024-06-27 11:02
Everything seem to work just find when using default configs. Without configuring urls

```javascript
export const rainbowConfig = getDefaultConfig({
    appName: 'PaalX Sniper🎯',
    projectId: PROJECT_ID,
    chains: [mainnet],
    ssr: false, // If your dApp uses server side rendering (SSR)
});
```

If you absolutely want to choose your own set of wallets, you can use `wagmi/connectors`

```javascript
import { connectorsForWallets, getDefaultConfig } from "@rainbow-me/rainbowkit";

import { mainnet } from "wagmi/chains";

import { createConfig, http } from "wagmi";
import { PROJECT_ID } from "@/utils/env";
import { metaMask, walletConnect } from "wagmi/connectors";
import {
    walletConnectWallet,
    metaMaskWallet,
    phantomWallet,

} from "@rainbow-me/rainbowkit/wallets";

const connectors = connectorsForWallets([
    {
        groupName: "Recommended",
        wallets: [metaMaskWallet, walletConnectWallet],
    },
], { projectId: PROJECT_ID, walletConnectParameters: {}, appName: "xxx", appDescription: "", appUrl: "", appIcon: "" });

const wagmiWallets = [walletConnect({
    projectId: PROJECT_ID, metadata: {
        name: 'xxxx',
        description: "xxxx",
        url: "https://xxxx.ai/",
        icons: [""]
    }
}), metaMask()]

function isMobileDevice() {
    return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
}
export const wagmiConfig = createConfig({
    connectors: isMobileDevice() ? wagmiWallets : connectors,
    chains: [mainnet],
    transports: {
        [mainnet.id]: http(''),
    },
});
```

In `main.tsx` 
```javascript
  <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    </WagmiProvider>
```

**Comment by magiziz** [comment] 2024-06-27 20:26
@weber77 Are you saying everything seems to work with `getDefaultConfig` ? If so that's great.

Here is another alternative to your `wagmi/connectors` approach:

```tsx
const connectors = connectorsForWallets(
  [
    {
      groupName: "Recommended",
      wallets: [metaMaskWallet, walletConnectWallet],
    },
  ],
  {
    projectId: "...",
    appName: "...",
    // Add your own WalletConnect parameters
    walletConnectParameters: {
      metadata: {
        name: "xxxx",
        description: "xxxx",
        url: "https://xxxx.ai/",
        icons: [""],
      },
    },
  }
);
```

**Comment by magiziz** [comment] 2024-07-02 18:53
Closing this issue for now. Feel free to re open this issue if you're still stuck.

**Closed by magiziz** 2024-07-02 18:53 UTC
